### ISSUE TITLE
onloadScript not rendering with non ajax command button if jstl type tag c:if is present on the page

### ISSUE THREAD

**Issue by vijpan** [omnifaces/omnifaces#366] opened 2017-03-17 03:33 UTC
**Env: Liberty App Server 16.0.0.4 (JEE 7 compliant), Primefaces 6.0, Omnifaces 2.6.1, Java 8
Alias: PrimeFaces - PF**

We have a scenario where we need both ajax and non ajax PF command buttons on the same page. On the same page we have few jstl type tags like c:if. On the main template we have both h:outputScript and o:onloadScript.

But o:onloadScript does not get rendered when we click non ajax button. If c:if tag is removed then everything is fine. 

To reproduce this i created a small poc (attached file poc war as poc.zip) - with a very simple case, where i am **logging in console inside h:outputScript and o:onloadScript** as shown in the code below. In this i have a c:if which always evaluates true

This xhtml has 2 command buttons, one is non-ajax  button - both of them execute a simple action and return to the same page.  The code inside o:onloadscript does not get logged in console.

XHTML source
a) faces/test/testonloadscript.xhtml

```
    <ui:composition 	xmlns="http://www.w3.org/1999/xhtml"
      					xmlns:h="http://xmlns.jcp.org/jsf/html"
      					xmlns:f="http://xmlns.jcp.org/jsf/core"
      					xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      					xmlns:c="http://xmlns.jcp.org/jsp/jstl/core" 
      					xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      					xmlns:p="http://primefaces.org/ui"      					
      					xmlns:o="http://omnifaces.org/ui"
      					xmlns:a="http://test/ui"
      				template="../template/templateLayout.xhtml">
	   	
   		<ui:define name="title">
			Test Title
		</ui:define>			
			
		<ui:define name="content">								
			<h:form >			
                <c:set var="_C" value="#{testOnLoadScript}" scope="request"/>
				<p:messages id="messages" />  				
				<br/>				
				<p:panelGrid columns="2" >                   
                    <f:facet name="header">
                    	Testing On Load Script
                    </f:facet> 					

					<h:outputText value="Testing On Load Script1"/>					
					<h:outputText value="Testing On Load Script2"/>	
						                    
                    <f:facet name="footer">                      
				        <p:commandButton value="Save-Ajax True" icon="ui-icon-check"  action="#{_C.save}" update="@form" />
				        <p:commandButton value="Save- Ajax False" icon="ui-icon-check"  action="#{_C.saveNonAjax}" ajax="false" />  				        	
				    </f:facet> 
                </p:panelGrid>
				
				<c:if test="#{_C.check}" >
					<h:outputText value="Value inside c:if "/>
				</c:if>
				
				<h:outputScript >
					console.log('hello called inside h:outputScript');
				</h:outputScript>
				
				<o:onloadScript>
	    			      console.log('hello called inside o:onloadScript');
	    		        </o:onloadScript>		    										
                
			</h:form>						
			 									
        </ui:define>
</ui:composition>

```
Controller class java source code
b)test.TestOnLoadScript

```
package test;

import java.io.Serializable;
import java.util.concurrent.atomic.AtomicLong;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;


@Named
@ViewScoped
@SuppressWarnings("serial")
public class TestOnLoadScript implements Serializable {
	
	private AtomicLong counter;

	public TestOnLoadScript() {
	}
	
	@PostConstruct
	public void initializeController() {
		this.counter = new AtomicLong();
	}

	public String save(){		
		FacesMessage msg = new FacesMessage("Save action executed=" + counter.incrementAndGet());
		FacesContext.getCurrentInstance().addMessage(null, msg);
		return null;
	}

	public String saveNonAjax() {
		FacesMessage msg = new FacesMessage("Save non ajax action executed=" + counter.incrementAndGet());
		FacesContext.getCurrentInstance().addMessage(null, msg);
		return null;
	}

	public boolean isCheck() {
		return true;
	}

}

```
Not sure what is going wrong?
[poc.zip](https://github.com/omnifaces/omnifaces/files/849584/poc.zip)

**Comment by BalusC** [comment] 2017-03-18 08:45
Reproduced. Thanks for the issue report and poc!

**Comment by vijpan** [comment] 2017-03-25 02:56
Just wondering if the fix for this will be a part of 2.6.2? or it will only be done as part of omnifaces 3+?

**Comment by BalusC** [comment] 2017-03-25 19:59
Problem appears to only manifest in MyFaces. I can't reproduce it in Mojarra. I'd have to debug in both impl sources to figure out what's going on and that may require a bit of time.

**Comment by vijpan** [comment] 2017-03-27 03:14
Thanks for looking into this!

**Comment by vijpan** [comment] 2017-08-17 02:27
Any idea when you might have some time to look into this?

**Comment by BalusC** [comment] 2017-08-17 15:52
Some months ago I spent nearly a full day debugging in MyFaces 2.2.11 without any new clues. I at least remember it's related to "dynamic actions" during restore view in MyFaces which in turn was triggered by `ScriptFamily#moveToBody()` logic. I only couldn't find out why and how and where MyFaces was remembering that and undoing that during restore view.

**Comment by vijpan** [comment] 2017-08-18 15:35
So kind of a dead end :(

**Comment by BalusC** [comment] 2020-12-30 09:15
FYI: still reproducible in MyFaces 2.3.6.

**Comment by melloware** [comment] 2020-12-30 12:36
Adding @tandraschko since its MyFaces related...

**Comment by tandraschko** [comment] 2020-12-30 12:59
can this be reproduced without omnifaces? If someone could prepare a unittest for MF, i can check it.

**Comment by BalusC** [comment] 2021-01-13 13:57
@tandraschko this is the smallest reproducer I could create:

```
@FacesComponent(createTag = true)
@ListenerFor(systemEventClass = PostAddToViewEvent.class)
public class OnloadScript extends UIOutput {

    public OnloadScript() {
        setRendererType("javax.faces.resource.Script");
    }

    @Override
    public void processEvent(ComponentSystemEvent event) {
        FacesContext context = event.getFacesContext();
        UIViewRoot view = context.getViewRoot();

        if (context.isPostback() ? !view.getComponentResources(context, "body").contains(this) : event instanceof PostAddToViewEvent) {
            view.addComponentResource(context, this, "body");
        }
    }
}
```

```
<!DOCTYPE html>
<html lang="en"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
    xmlns:my="http://xmlns.jcp.org/jsf/component"
>
    <h:body>
        <my:onloadScript>
            document.getElementById('result').innerHTML='onloadScript successfully executed';
        </my:onloadScript>

        <h:form>            
            <h:commandButton value="non-ajax postback" />
        </h:form>                        

        <c:if test="#{true}">
            Remove this c:if and it will work.
        </c:if>

        <div id="result" />
    </h:body>
</html>
```

Instructions:
1. copy above code into empty project with MyFaces
2. open XHTML page in browser
3. observe that "onloadScript successfully executed" text is present
4. click "non-ajax postback" button
5. observe that "onloadScript successfully executed" text has unexpectedly disappeared
6. edit XHTML source to remove entire <c:if> tag
7. reopen XHTML page in browser
8. observe that "onloadScript successfully executed" text is present
9. click "non-ajax postback" button
10. observe that "onloadScript successfully executed" text is still present

**Comment by tandraschko** [comment] 2021-01-19 12:15
Created a issue in MF Jira now: https://issues.apache.org/jira/browse/MYFACES-4378

**Comment by tandraschko** [comment] 2021-01-19 13:18
@BalusC can't replicate, see https://issues.apache.org/jira/browse/MYFACES-4378

**Comment by BalusC** [comment] 2022-12-20 21:27
Sorry, the test case was not correct. The `<test:onloadScript>` was not compiled and ended up plain vanilla because the taglib was not registered. 
![image](https://user-images.githubusercontent.com/173372/208769879-06456730-e51c-4d92-a1c2-b3e97aa6a230.png)
![image](https://user-images.githubusercontent.com/173372/208770052-4d08e007-67ac-4d22-a1b5-60558a20c5c6.png)

---


Please use `@FacesComponent(createTag = true)` as instructed and adjust 
`xmlns:test` to `"http://xmlns.jcp.org/jsf/component"` as instructed. The taglib is not necessary for the reproducer.

This is the expected initial output:
![image](https://user-images.githubusercontent.com/173372/208769762-63bed72d-f144-4058-8d4b-ce3209d1a56a.png)

**Comment by BalusC** [comment] 2023-02-10 11:13
Closing off. Bug is in MyFaces.

**Closed by BalusC** 2023-02-10 11:13 UTC

**Comment by melloware** [comment] 2024-05-05 13:48
I updated the MyFaces ticket with reproducer and more info: https://issues.apache.org/jira/browse/MYFACES-4378
