### ISSUE TITLE
IllegalStateException when using scriptParam and viewAction in metadata

### ISSUE THREAD

**Issue by mhrnr** [omnifaces/omnifaces#671] opened 2022-02-16 06:28 UTC
I get the error "Component ID omnifaces_omnifaces_js has already been found in the view" when i use scriptParam and viewAction. Example:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:o="http://omnifaces.org/ui">
    <f:view>

        <f:metadata>
            <o:scriptParam script="window.screen.width"
                           value="#{bean.clientScreenWidth}"
                           render="@form"/>
            <f:viewAction action="#{bean.onload()}"/>
        </f:metadata>

        <h:body>
            <h:form>
                <h:outputText value="#{bean.clientScreenWidth}"/>
            </h:form>
        </h:body>
    </f:view>
</html>
```

I do not get the error, when i remove the viewAction.
Using Omnifaces 3.13 on Wildfly 21.

**Comment by BalusC** [comment] 2022-02-19 17:13
Norepro when using Mojarra 2.3.17 against empty web.xml.

Which JSF version exactly is your WildFly 21 using and are there any non-defaults configured in web.xml? Perhaps state saving related?

**Comment by BalusC** [comment] 2022-02-20 09:34
Ok I reproduced it when using `@org.omnifaces.cdi.ViewScoped` on the bean instead of the presumed `@RequestScoped`. It turns out that dynamically adding `jsf.js` and `omnifaces.js` went wrong. The one tried to add them to head, but the other tried to search for existing ones in body. When fixing this lookup, the placement of scripts was also after all wrong, the omnifaces.js was in head but jsf.js was in body while it should be BEFORE omnifaces.js.

**Comment by BalusC** [comment] 2022-02-20 10:43
All fixed now. It was quite a corner case which would have been workaroundable by explicitly declaring jsf.js in head:
```
<h:head>
    <h:outputScript library="javax.faces" name="jsf.js" target="head" />
</h:head>
```
But that should indeed not have been necessary. Thank you for reporting this issue and improving OmniFaces!

**Closed as completed by BalusC** 2022-02-20 10:43 UTC
