### ISSUE TITLE
o:validator - disable with ajax not working

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#486] opened 2018-10-03 02:21 UTC
Some years ago i had the requirement to disable validator depending on a selected type, which works with _o:validator_ _disabled_ attribute but has some drawbacks.

https://stackoverflow.com/questions/10677984/disable-validator-via-ajax

**Use case**

1.  user inputs address
2.  user changes type to e-mail

**A) Does not works without ajax onchange**

With a simple submit button of the form it does not work since _type_ was not processed yet and validator not updated. So the validator is not active. 

*Idea*:

Validator would need to work on a copy of the bean similar to _validateBean_ in this case. 

**B) User enters input in validated field first**

This will remove the input since it was not processed with _p:ajax process="@this, type"_.

Processing also the _address_ input with _process="@this, type, address" does not work since validation of _address_ occurs before _type_ processing. If current input is invalid also _type_ will not be processed.

*Idea*: 

If validator component would have an _id_ or is allowed outside of _EditableValueHolder_ it could be updated manually like _p:ajax process="@this, type, addressValidator"_.

*Workaround*:

The safe way is to force the user to select the type first, but depending on the design this is not always a good idea.

**Comment by BalusC** [comment] 2019-04-07 16:25
I'm confused. I cannot reproduce your problem. Even when using plain f:validator.

Only thing I had to change is to remove `<p:ajax update="formId:address">` from the "type" input because it clears out the address field.

**Comment by BalusC** [comment] 2019-10-27 15:17
Closing off as norepro/norespons.

**Closed by BalusC** 2019-10-27 15:17 UTC
