### ISSUE TITLE
SelectItemsIndexConverter null and empty String check

### ISSUE THREAD

**Issue by oliverjstein** [omnifaces/omnifaces#365] opened 2017-03-15 16:35 UTC
Hi,
why does the SelectItemsIndexConverter not check the submittedValue for null or empty String in getAsObject?

We currently have the problem that primefaces does not display the itemLabel of noSelectOption if the itemValue is null:

```<p:selectOneMenu id="unit" value="#{searchInfoPointController.unitToMatch}" converter="omnifaces.SelectItemsIndexConverter" panelStyle="width:180px" var="u" style="width:190px" filter="true" filterMatchMode="startsWith">```

`<f:selectItem itemValue="#{null}" itemLabel="#msg['general.selectItem.noSelectionOption']}" noSelectionOption="true"/>`

```
<f:selectItems value="#{searchInfoPointController.units}" var="unit" itemLabel="#{unit.name}" itemValue="#{unit}"/>
	<p:column>
		<h:outputText value="#{u.name}"/>
	</p:column>
	<p:column>
		<h:outputText value="#{u.measurand.name}"/>
	</p:column>
</p:selectOneMenu>
```

In order that primefaces shows the value of noSelectionOption we have to set itemValue to the empty String. But then the converter gets called a second time by validateValue with the empty String and throws a NumberFormatException.

Kind regards

**Comment by BalusC** [comment] 2017-03-18 08:27
The `noSelectionOption="true"` is not correctly used here.
Remove it and if necessary use `required="true"` instead.
See also http://stackoverflow.com/q/11360030/157882

**Comment by oliverjstein** [comment] 2017-03-18 11:42
thx for the response but it does not chang anything.
primefaces SelectOneMenu and SelectOneMenuRenderer call converters getAsObject multiple times as soon as p:colum is used. One of the calls includes an empty string for submittedValue (even if it is not empty).
It is definitley a primefaces issue (more often than not) but it would be good if the omnifaces converter would check for null or empty string.
Anyway i solved it by extending SelectItemsIndexConverter:

`
public class SafeSelectItemsIndexConverter extends SelectItemsIndexConverter {

    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String submittedValue) {
        if (submittedValue == null || submittedValue.isEmpty()) {
            return null;
        }
        return super.getAsObject(context, component, submittedValue);
    }
}`

**Comment by BalusC** [comment] 2017-04-04 05:06
Sorry, I really can't reproduce your problem.

Which JSF impl/version and PF version are you using?

**Comment by oliverjstein** [comment] 2017-04-18 16:50
Thx, but never mind.
We are using mojarra 2.2.14, primefaces-elite 6.0.17 and omnifaces 2.6
PF people fixed the issue:
https://github.com/primefaces/primefaces/issues/2207

kind regards

**Comment by BalusC** [comment] 2017-05-07 07:28
Closing off as bug was in PrimeFaces side and already fixed over there.

**Closed by BalusC** 2017-05-07 07:28 UTC
