### ISSUE TITLE
ValidateBean: page rendering breaks when a property can't be set

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#757] opened 2023-05-17 09:07 UTC
Environment:
mojarra-4.0.1
omnifaces-4.1
tomcat 10.1.2

Reproduction steps:
Create a java bean with an Integer field
Create a Costraint and a ConstraintValidator for the bean
Make a JSF page with a form and composite input component bound to the integer property
Add an o:validateBean with class value
Write a letter in the input and submit the form
Result:
<details><summary>Stack trace:</summary>
<code>org.omnifaces.taghandler.ValidateBean$ValidateBeanCallback.run Exception occured while doing validation.
	java.lang.IllegalStateException: java.lang.IllegalArgumentException: argument type mismatch
		at org.omnifaces.util.Reflection.setBeanProperty(Reflection.java:359)
		at org.omnifaces.util.Reflection.setProperty(Reflection.java:350)
		at org.omnifaces.util.Reflection.setBeanProperties(Reflection.java:306)
		at org.omnifaces.taghandler.ValidateBean$3.invoke(ValidateBean.java:456)
		at org.omnifaces.taghandler.ValidateBean$ValidateBeanCallback.run(ValidateBean.java:751)
		at org.omnifaces.util.Events.lambda$wrap$1(Events.java:334)
		at org.omnifaces.util.Events$4.afterPhase(Events.java:370)
		at org.omnifaces.eventlistener.CallbackPhaseListener.afterPhase(CallbackPhaseListener.java:69)
		at com.sun.faces.lifecycle.Phase.handleAfterPhase(Phase.java:148)
		at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:78)
		at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
		at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
		at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
		at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:829)
	Caused by: java.lang.IllegalArgumentException: argument type mismatch
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
		at org.omnifaces.util.Reflection.setBeanProperty(Reflection.java:356)
		... 37 more
</code>
</details>

I can try to arrange a small reproducer if needed.

**Comment by BalusC** [comment] 2023-05-20 11:51
Sorry, I cannot reproduce it. It already fails with a conversion error before the validator is hit.

```
@Named
@RequestScoped
@BeanConstraint
public class Bean {

    private Integer value;

    public void submit() {
        System.out.println("Submit: " + value);
    }

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }
}
```

```
@Constraint(validatedBy=BeanConstraintValidator.class)
@Target({ TYPE, METHOD, FIELD })
@Retention(RUNTIME)
public @interface BeanConstraint {
    String message() default "invalid";
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};
}
```

```
public class BeanConstraintValidator implements ConstraintValidator<BeanConstraint, Bean> {

    @Override
    public void initialize(BeanConstraint constraint) {
        //
    }

    @Override
    public boolean isValid(Bean bean, ConstraintValidatorContext context) {
        System.out.println("isValid: " + bean.getValue());
        return true;
    }
}
```

```
<h:form>
    <cc:inputComposite value="#{bean.value}" />
    <h:commandButton id="submit" value="submit" action="#{bean.submit}">
        <f:ajax execute="@form" render="@form" />
    </h:commandButton>
    <o:validateBean value="#{bean}"  />
    <h:messages />
</h:form>
```

```
<cc:interface>
    <cc:attribute name="value" />
</cc:interface>
<cc:implementation>
    <h:inputText id="input" label="input" value="#{cc.attrs.value}" />
    <h:message id="message" for="input" />
</cc:implementation>
```
![image](https://github.com/omnifaces/omnifaces/assets/173372/6f686f16-4e39-4fba-9596-b1543f09c368)

**Comment by NicolaIsotta** [comment] 2023-05-20 12:42
I'll try to create a standalone reproducer

**Comment by NicolaIsotta** [comment] 2023-05-20 14:38
Here's the reproducer:
[test-bv-error.zip](https://github.com/omnifaces/omnifaces/files/11522537/test-bv-error.zip)
to run: `mvn jetty:run` and navigate to [http://localhost:8080/test-bv-error/](http://localhost:8080/test-bv-error/)

The input component has attached a converter which doesn't throw ConverterException, but the input is validated by a f:longRangeValidator so everything runs smoothly if o:validateBean is not present.

I know this is a corner case, but shouldn't o:validateBean be executed after all the standard validators?

**Comment by BalusC** [comment] 2023-05-20 15:30
Ah ok so there should be a bogus converter ;) I'll take a second look.

**Comment by BalusC** [comment] 2023-05-20 15:55
No, I won't fix this issue in OmniFaces side. Your converter is indeed wrong. Please use `Converter<Integer>` instead of a untyped one. Then it will automatically show a compilation error. Then fix your converter to return `null` or `0` or perhaps `-1` in the catch block.

**Closed as completed by BalusC** 2023-05-20 15:55 UTC

**Comment by NicolaIsotta** [comment] 2023-05-20 16:06
I modified the converter (it was a leftover from a JSF1.2 app porting) and now o:validateBean does not complain.

BTW, I took a look at ValidateBean code and noticed one thing in ValidateBeanCallback
https://github.com/omnifaces/omnifaces/blob/b8f5cff812334899a8c29b93cc3a0bf832d6b42e/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L746-L767
shouldn't `invoke()` have `throws Exception` since `run()` has a `catch`?

**Comment by BalusC** [comment] 2023-05-21 13:14
No, the catch block should catch `RuntimeException` instead.
