### ISSUE TITLE
CombinedResourceHandler; JavaScript; Safari does not send cookies

### ISSUE THREAD

**Issue by christophs78** [omnifaces/omnifaces#537] opened 2020-01-17 11:04 UTC
We run into the following issue with Safari on iOS/iPadOS 13 and MacOS
![grafik](https://user-images.githubusercontent.com/10461942/72607404-e1e77300-3920-11ea-888f-b6b3ddb3543b.png)

Safari can´t load the combined JS through our portal. Because safari does not send the session-cookie for this request. (Our portal sends HTTP 401.) All other "normal" JS-requests work fine.
Everything is loaded from the same Domainname. But it looks like Safari detects the combined JS as suspicious.

Think it would help to have separate switches to enable/disable CombinedResourceHandler for CSS and JS.

**Comment by BalusC** [comment] 2020-01-25 15:11
It's unexpected that the server returns 401 for a combined resource without session cookie. I can understand a 500 if the problem was caused by the combined resource handler. But the combined resource handler is absolutely stateless. It is not dependent on HTTP session at all.

401 basically means that a non-logged-in user is requesting a restricted resource. It's unexpected that there are logged-in user restrictions on CSS/JS resources. Perhaps you are unintentionally filtering for logged-in users on incoming `/javax.faces.resource/*` requests as well? In this case, you should adjust the login filter or web.xml to explicitly allow all `/javax.faces.resource/*` requests without logged-in user.

See also https://stackoverflow.com/q/13822978/157882

**Comment by christophs78** [comment] 2020-01-25 17:34
The application (server) is behind a portal-server which acts as reverse-proxy. The portal-server controls access to our whole application. (The whole application is restricted.)
Because of the missing portal-session-cookie our portal sends HTTP 401. (It block´s the request before rewriting to the application (server).
We looked a bit deeper into the script-tag generated by CombinedResourceHandler.
Maybe Safari 13 misinterprets `crossorigin="anonymous"` generated by CombinedResourceHandler. We checked this against https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin.
MDN says `crossorigin="anonymous"` is only relevant for CORS-requests. In our usecase alll requests are against the some (portal-)domainname. So we should not have any CORS-issues.
After we disabled CombinedResourceHandler all JS-files were served to Safari 13 as expected. At this point we stopped our research. From my feeling it may be a Safari- edge-case-issue/bug/limitation caused by  the unusual name of the JS-file generated by CombinedResourceHandler or by misinterpreted `crossorigin="anonymous"`.

**Comment by BalusC** [comment] 2020-03-22 14:23
I've made that attribute configurable. Can you try today's 3.5-SNAPSHOT with following in web.xml?
```
<context-param>
	<param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_CROSSORIGIN</param-name>
	<param-value>use-credentials</param-value>
</context-param>
```

**Comment by christophs78** [comment] 2020-03-27 06:49
Thanks for your update and thanks for putting effort into this issue.

Currently it´s hard to test this with 3.5-SNAPSHOT on MacOS with Safari. We are due to Corona in homeoffice, where only Windows is available to me. I´ll update you as soon as i´m able to check this on MacOS and Safari.

One other (off topic) question: You are one of the guys involved in moving the JSF-Spec forward?
Can you have a look at https://files.gitter.im/primefaces/primefaces/Cfij/JSF_components_quo_vadis_2020.pdf?
I tried to write down some vague ideas how to move JSF-components forward? Do you have some high-level-oppinion about this? Is this something we may think about, is it out of reach, is it a bad idea, ... ?

**Comment by BalusC** [comment] 2020-04-04 10:17
The bloatness of taglib.xml was indeed high in the list of things to be tackled. One of the ideas was to replace them by new annotations.

**Comment by melloware** [comment] 2020-05-05 22:32
@BalusC was this released in 2.75 and 3.6?

**Comment by BalusC** [comment] 2020-05-06 08:42
2.7.4 / 3.5

**Comment by melloware** [comment] 2020-06-29 12:58
@christophs78 did you test this is it safe to close?

**Comment by christophs78** [comment] 2020-06-29 19:09
I still have issues to validate this in my homeoffice. Tried this with my private windows notebook and ipad. But it does not offers new findings. (PrimeFaces Showcase does not seem to work with CombinedResourceHandler in general.)

Maybe some owner of a macbook with safari 13 may help out.
We should see whether safari send´s cookies like JSESSION-ID with the request fetching the JS-file. 
For edge or chrome it looks like this:
![image](https://user-images.githubusercontent.com/10461942/86044993-399b1600-ba4b-11ea-8505-db305460255d.png)

When we look at the first screenshot of safari-dev-tools this cookies has not been sent in the initial constellation.

For our in-house enterprise-framework we disabled combined resource handler. Partially because of this issue. Partially because it does not make this much sense together with PrimeFaces for a large enterprise scale application. (Different XHTML´s use different PrimeFaces-components. Often each XHTML need´s it´s own combined CSS and/or JS. For this situations it may be better to leave it uncombined to allow browsercache to do it´s work.)

**Comment by melloware** [comment] 2020-11-25 17:28
@christophs78 Still not able to validate this one?

**Comment by christophs78** [comment] 2020-12-30 08:10
IMO we can close this ticket. Thanks @BalusC for implementing this.

Did some test´s with my iPad (iOS 14) against my dev-workstation. As of iOS 14 / Safari 14 (`user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15`) Safari sends JSESSIONID as expected. (Only limitation is, that i´m not able to test this including our corporate reverse proxy.)

```
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - host: 192.168.0.12:8080
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - origin: http://192.168.0.12:8080
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - cookie: JSESSIONID=2F954A387C0C892E927A5C69C973BF17; oam.Flash.RENDERMAP.TOKEN=-1a2fyunxzq
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - connection: keep-alive
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - accept: */*
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - accept-language: de-at
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - referer: http://192.168.0.12:8080/primefaces-test/
/primefaces-test/javax.faces.resource/eNp1yksOgCAQA9ATKXtvQ6CYQT7jAAsTD6-JCxIMqzbtY6EIpw3K5s8GudQXqy83T76FQ9splcGYLPhNkXNCqqO1uoLJHBDV62AcBTQOWVvV62seTZ1HoQ.js - Header - accept-encoding: gzip, deflate
```

And for (future?) corner-cases we are now able to set 
```
<context-param>
    <param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_CROSSORIGIN</param-name>
    <param-value>use-credentials</param-value>
</context-param>
```
if needed.

**Comment by BalusC** [comment] 2020-12-30 08:21
Thanks for feedback!

**Closed by BalusC** 2020-12-30 08:21 UTC
