### ISSUE TITLE
<o:socket> Browser / Client auto-reconnects indefinitely after session timeout

### ISSUE THREAD

**Issue by ramberg** [omnifaces/omnifaces#503] opened 2019-03-07 10:18 UTC
With Omnifaces 3.2 various Browser-Windows-Combinations are indefinitely trying to reconnect the web socket after a session timeout occurred. The reconnect happens with a very high frequency; between 500 and 1000 reconnects per seconds on a local network, and between 2 and 10 over the internet. The on-close seems to not being properly processed by the browser. Downgrading to Omnifaces 3.1 resolves this.

The issue seems to be predominant with older Internet Explorer or Edge Versions in various Windows Versions. Observed Browser Agents with said issue:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063 --> Windows 10, Version 1703 (Build 15063.1446)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299
Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko

**Comment by BalusC** [comment] 2019-04-28 11:57
I grabbed an IE11 (`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`), but I cannot reproduce it.

The difference between 3.1 and 3.2 is that the session expiration now explicitly removes the channel detail from server's memory. Previously this was not the case and caused memory leaks. Normally, when the session is expired in server, then the channel is closed by server with code 1000 and reason "Expired". Or, when the client connects to a non-existent channel, then the channel is closed by server with code 1008. In your cases, the close with code 1000 appears to be failing and the client is reconnecting nonetheless, and this succeeded in 3.1 because the channel was not explicitly removed.

The push script is written so that when the channel is NOT closed with code 1000 or 1008, then it will automatically reconnect. However, close code detection appears to be failing in your cases. But I have thus not been able to reproduce it. If I were able to reproduce it, then I would have placed a breakpoint in the onclose function of push script in omnifaces.js and inspected the actual code and reason.

Have you been able to reproduce it yourself?

**Comment by ramberg** [comment] 2019-04-30 10:53
I was able to monitor the behavior with clients broadcasting your mentioned agent string of IE11, but was unable to reproduce it using IE. It seemed to be heavily correlated with the Build Version of Windows. As I was unable to detect the Build Version of our clients using IE, I analysed all clients using Edge. The problem seemed to be present until Edge Version 41.16299.15. I was able to find a Windows machine using Edge 40.15063, which corresponds to Windows 10, Version 1703 (Build 15063.1446), and was successful in reproducing the problem. As I was able to "eliminate" this issue by downgrading Omnifaces, I did not test other browser agents, at that time. After allowing Windows to upgrade itself to 1803, with Edge 42, the problem went away.

The issue appears to be predominantly present for clients using various flavors of IE in various versions of windows (7, 8.1 and 10) and Edge until 41; with some rare Chrome clients exhibiting the issue. Almost all Firefox and Chrome clients seem to be "immune". Unfortunately, it seems that most of our clients are using older builds of Windows with Edge or IE and are generating 10th of millions of those requests per day, when upgrading back to Omnifaces to 3.2.

If you need additional tests or additional information, do not hesitate to ask.

**Comment by BalusC** [comment] 2019-05-04 15:34
Nailed it in a VM with Edge 41.16299.15. The error code 1008 was incorrectly interpreted as 1005. 

![image](https://user-images.githubusercontent.com/173372/57181281-aa529c80-6e5f-11e9-8820-3b2262e34613.png)

However, the message "Unknown channel" was correct, so I've adjusted the script to check that as fallback.

**Closed** 2019-05-04 15:33 UTC
