### ISSUE TITLE
InputFile uses unmodifiableList and it causes java.lang.NoSuchMethodException

### ISSUE THREAD

**Issue by karlkilden** [omnifaces/omnifaces#364] opened 2017-03-15 08:00 UTC
Might be a bug in myfaces but I have the following scenario

TomEE 7 with Myfaces 2.2.9

A form with multiple inputs including fileupload with multiple=true. When the form is posted a a required field is missing (just required=true) the faces message is displayed as expected. If I post again (ajax both times with render @form) then I get the following exception:

```
java.lang.NoSuchMethodException: java.util.Collections$UnmodifiableRandomAccessList.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	at javax.faces.component.UIComponentBase.restoreAttachedState(UIComponentBase.java:1873)
	at javax.faces.component._DeltaStateHelper.restoreState(_DeltaStateHelper.java:772)
	at javax.faces.component.UIComponentBase.restoreState(UIComponentBase.java:2080)
	at javax.faces.component.UIOutput.restoreState(UIOutput.java:241)
	at javax.faces.component.UIInput.restoreState(UIInput.java:1060)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:878)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreStateFromMap(DefaultFaceletsStateManagementStrategy.java:897)
	at org.apache.myfaces.view.facelets.DefaultFaceletsStateManagementStrategy.restoreView(DefaultFaceletsStateManagementStrategy.java:433)
	at org.apache.myfaces.application.StateManagerImpl.restoreView(StateManagerImpl.java:133)
	at org.apache.myfaces.shared.view.ViewDeclarationLanguageBase.restoreView(ViewDeclarationLanguageBase.java:104)
	at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.restoreView(FaceletViewDeclarationLanguage.java:2140)
	at org.apache.myfaces.application.ViewHandlerImpl.restoreView(ViewHandlerImpl.java:336)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:82)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:82)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:82)
	at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:106)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:82)
	at org.apache.myfaces.lifecycle.RestoreViewExecutor.execute(RestoreViewExecutor.java:170)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:196)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at org.apache.deltaspike.jsf.impl.listener.request.DeltaSpikeLifecycleWrapper.execute(DeltaSpikeLifecycleWrapper.java:89)
	at javax.faces.lifecycle.LifecycleWrapper.execute(LifecycleWrapper.java:46)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.openejb.server.httpd.WebBeansFilter.doFilter(WebBeansFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.deltaspike.servlet.impl.event.EventBridgeFilter.doFilter(EventBridgeFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.deltaspike.servlet.impl.produce.RequestResponseHolderFilter.doFilter(RequestResponseHolderFilter.java:63)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.omnifaces.filter.GzipResponseFilter.doFilter(GzipResponseFilter.java:181)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.omnifaces.filter.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:124)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
```

It only happens when I have the fileUpload and since it uses return unmodifiableList(convertedParts); in getConvertedValue it seems to be what is causing my problem

**Comment by karlkilden** [comment] 2017-03-16 12:33
Problem might be 	/**
	 * @see Faces#getRequestParts(String)
	 */
	public static Collection<Part> getRequestParts(FacesContext context, String name) {
		try {
			List<Part> parts = new ArrayList<>();

			for (Part part : getRequest(context).getParts()) {
				if (name.equals(part.getName())) {
					parts.add(part);
				}
			}

			return parts;
		}
		catch (ServletException | IOException e) {
			throw new FacesException(e);
		}
	}

**Comment by BalusC** [comment] 2017-03-18 07:26
I wonder why it's saved in JSF state in first place.

**Comment by BalusC** [comment] 2017-03-18 08:08
A reproducer would be helpful. I can't reproduce the problem with below SSCCE on stock TomEE 7.0.3 with minimal settings.

```
<h:form enctype="multipart/form-data">
	<h:inputText required="true" />
	<o:inputFile multiple="true" />
	<h:commandButton><f:ajax execute="@form" render="@form" /></h:commandButton>
	<h:messages />
</h:form>
```

I clicked the button at least twice, but no exception.

**Comment by karlkilden** [comment] 2017-03-20 10:14
It is unrelated to unmodifiableList. It only happens after validation failure for accept. I will try to make a reproducer

**Comment by BalusC** [comment] 2017-04-04 05:07
Any luck?

**Comment by BalusC** [comment] 2017-05-20 19:40
Closing off as norepro. Once you have a reproducer feel free to open a new issue.

**Closed by BalusC** 2017-05-20 19:40 UTC
