### ISSUE TITLE
Clustering issue with OmniFaces Converter due to it being non-serializable

### ISSUE THREAD

**Issue by beikov** [omnifaces/omnifaces#575] opened 2020-10-02 13:49 UTC
When persisting a session that was using Omnifaces `o:converter` I get the following exception:

```
15:28:29,509 WARN  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 228)  WFLYUT0024: Failed to persist session attribute org.apache.myfaces.application.viewstate.ServerSideStateCacheImpl.SERIALIZED_VIEW with value org.apache.myfaces.application.viewstate.SerializedViewCollection@729191ee for session W9i0HvHXAF1khRYPtx2iyG_IJMUkMYpCsnOvIeAR: java.io.NotSerializableException: org.omnifaces.taghandler.Converter
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:860)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:778)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:778)
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:271)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:976)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:778)
	at org.jboss.marshalling.river.BlockMarshaller.doWriteObject(BlockMarshaller.java:65)
	at org.jboss.marshalling.river.BlockMarshaller.writeObject(BlockMarshaller.java:56)
	at org.jboss.marshalling.MarshallerObjectOutputStream.writeObjectOverride(MarshallerObjectOutputStream.java:50)
	at org.jboss.marshalling.river.RiverObjectOutputStream.writeObjectOverride(RiverObjectOutputStream.java:179)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:344)
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.marshalling.reflect.SerializableClass.callWriteObject(SerializableClass.java:271)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:976)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteFields(RiverMarshaller.java:1032)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteSerializableObject(RiverMarshaller.java:988)
	at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:854)
	at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
	at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:111)
	at org.wildfly.extension.undertow.AbstractPersistentSessionManager.persistSessions(AbstractPersistentSessionManager.java:77)
	at io.undertow.servlet.handlers.SessionRestoringHandler.stop(SessionRestoringHandler.java:108)
	at io.undertow.servlet.core.DeploymentManagerImpl.stop(DeploymentManagerImpl.java:548)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.stopContext(UndertowDeploymentService.java:141)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$2.run(UndertowDeploymentService.java:121)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: an exception which occurred:
	in field this$0
	in field _serializedViews
	in object org.apache.myfaces.application.viewstate.SerializedViewCollection@729191ee
```

I'm using MyFaces 2.3.4 but also tried with 2.3.6 and Omnifaces 2.6.9

**Comment by beikov** [comment] 2020-10-02 13:57
AFAICT the usage that is problematic is the following:

```
            <p:autoComplete id="transportOrderCustomer"
                            value="#{transportOrderWizardModel.model.customer}"
                            var="customer"
                            itemLabel="#{customer.name}"
                            itemValue="#{customer}"
                            completeMethod="#{transportOrderWizardModel.completeCustomerSearch}">
                <p:ajax event="itemSelect" process="@this" listener="#{transportOrderWizardModel.onCustomerSelect}"/>
                <o:converter converterId="omnifaces.ListConverter" list="#{transportOrderWizardModel.customerItems}"/>
            </p:autoComplete>
```

**Comment by BalusC** [comment] 2020-10-03 09:37
That can happen if `javax.faces.PARTIAL_STATE_SAVING` is `false`.

Can you check your `web.xml`?

**Comment by BalusC** [comment] 2020-10-03 10:39
If that's not the cause, you can always try if OmniFaces 2.7.8-SNAPSHOT or 3.8.1-SNAPSHOT solves your problem. I've just made some improvements to actually support `javax.faces.PARTIAL_STATE_SAVING=false`

**Comment by beikov** [comment] 2020-10-05 23:07
Partial state saving is active. The fix in the SNAPSHOT works though! Thanks. Looking forward to a release!

**Comment by BalusC** [comment] 2020-10-24 12:51
Great. Closing off then.

**Closed as completed by BalusC** 2020-10-24 12:51 UTC
