### ISSUE TITLE
Quarkus: org.omnifaces.FACES_VIEWS_SCAN_PATHS not working when run in Production Mode

### ISSUE THREAD

**Issue by tmulle** [omnifaces/omnifaces#708] opened 2022-09-15 18:32 UTC
When turning on the URL shortening in a Quarkus web application using [ExtensionlessURLS](https://showcase.omnifaces.org/facesviews/ExtensionlessURLs), the URLS are correctly shortened when run with in DEV mode:

`mvn compile quarkus:dev`

When run in "Production Mode" like below, the URLS are NOT shortened anymore.
`mvn clean package && java -jar target/quarkus-app/quarkus-run.jar`

I made a [Demo](https://github.com/tmulle/quarkus-faces) of the demo project which is originally from @melloware and I just added the section to the `web.xml`:

```
<context-param>
        <param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
        <param-value>/*.xhtml</param-value>
    </context-param>
```

To Test:

1. Start Quarkus in DEV mode and go to http://localhost:8080 and notice the URLS in the browser will not have the `*.xhtml` extensions

2. Start Quarkus in PROD mode and do the same test and you'll notice that the extensions (*.xhtml) are no longer stripped off

**Comment by melloware** [comment] 2022-09-15 19:04
From looking @BalusC it looks like in Developement mode everything is scanned but in Production Mode you exclude META-INF folders which is where Quarkus stores its XHTML files?

```java
private boolean filterExtensionLess(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws IOException, ServletException
    {
        String servletPath = request.getServletPath();

        if (!isExtensionless(servletPath)) {
            return false;
        }

        ServletContext servletContext = getServletContext();
        boolean multiViews = isMultiViewsEnabled(request);
        Map<String, String> resources = getMappedResources(servletContext);
        String normalizedServletPath = stripTrailingSlash(servletPath);
        String resource = normalizedServletPath + (multiViews ? "/*" : "");

        if (getApplicationFromFactory().getProjectStage() == Development && !resources.containsKey(resource)) {
            // Check if the resource was dynamically added by scanning the faces-views location(s) again.
            resources = scanAndStoreViews(servletContext, false);
        }

        if (multiViews && !resources.containsKey(resource)) {
            if (request.getPathInfo() != null) {
                servletPath += request.getPathInfo();
            }

            resource = getMultiViewsWelcomeFile(servletContext, resources, servletPath);

            if (resource != null) {
                String pathInfo = servletPath.substring(resource.substring(0, resource.lastIndexOf('/')).length());
                request.setAttribute(FACES_VIEWS_ORIGINAL_PATH_INFO, pathInfo.isEmpty() ? "/" : pathInfo);
                request.getRequestDispatcher(resource).forward(request, response);
                return true;
            }
        }

        return filterExtensionLess(request, response, chain, resources, resource, normalizedServletPath);
    }
```

**Comment by tmulle** [comment] 2022-09-15 19:20
Not sure if this is another issue, but when running under Quarkus, this section of code doesn't find the `web.xml` and the resulting list of welcome files is always empty. At least that's what it showed me in the debugger when I start up the application in debug mode.

In `org.omnifaces.facesviews.FacesViews`
```java
private static void scanAndStoreWelcomeFiles(ServletContext servletContext) {
		URL webXml;

		try {
			webXml = servletContext.getResource("/WEB-INF/web.xml");
		}
		catch (MalformedURLException e) {
			throw new IllegalStateException(e);
		}

		Set<String> mappedWelcomeFiles = new LinkedHashSet<>();

		for (String welcomeFile : getNodeTextContents(webXml, "welcome-file-list/welcome-file")) {
			if (isExtensionless(welcomeFile)) {
				mappedWelcomeFiles.add(addLeadingSlashIfNecessary(stripTrailingSlash(welcomeFile)));
			}
		}

		servletContext.setAttribute(MAPPED_WELCOME_FILES, unmodifiableSet(mappedWelcomeFiles));
	}
```

**Comment by melloware** [comment] 2022-09-15 19:58
In `WebXmlSingleton.java` there is this...

```java
private static final String WEB_XML = "/WEB-INF/web.xml";
private static final String QUARKUS_WEB_XML = "META-INF/web.xml";
private static final String WEB_FRAGMENT_XML = "META-INF/web-fragment.xml";
```

Anywhere WEB_XML is used we also need to use QUARKUS_WEB_XML

**Comment by melloware** [comment] 2022-09-15 21:40
I think I fixed the Welcome Files issue with my PR but not the EXTENSIONLESS mapping issue.  see: https://github.com/omnifaces/omnifaces/pull/709

**Comment by BalusC** [comment] 2022-09-16 09:14
See my comments on https://github.com/melloware/omnifaces/commit/bab0d2e2201ef1cc4b80d63791e4c37d7af3ceb2. This doesn't work on some servers because `ServletContext` is not per definition injectable at the moment `FacesViews` gets initialized. Integration tests are failing on WildFly and Payara for this reason.

**Comment by melloware** [comment] 2022-09-16 09:20
Ok I will switch it back and just parse both locations here

**Comment by melloware** [comment] 2022-09-16 12:08
OK I refactored to do the lookup using the constants.  Next I need to debug the org.omnifaces.FACES_VIEWS_SCAN_PATHS issue.

**Comment by melloware** [comment] 2022-09-16 14:36
OK I debugged it and I can't tell if its a Quarkus bug or not but the issue is this line of code `servletContext.getResourcePaths(resourcePath)`

That if you pass `servletContext.getResourcePaths("/")`  will return all mapped resources for the filter to then replace.  This works fine in DEV mode as you can see the logs below.  But when running in Quarkus PROD mode that returns an `empty set`

**DEV MODE:**
```
2022-09-16 10:30:44,019 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) registerForwardingFilter
2022-09-16 10:30:44,019 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) First scan welcome files in web.xml
2022-09-16 10:30:44,067 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan our dedicated directory for Faces resources that need to be mapped.
2022-09-16 10:30:44,068 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) scanAndStoreViews: true
2022-09-16 10:30:44,077 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) rootPath: /
2022-09-16 10:30:44,077 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) extension: .xhtml
2022-09-16 10:30:44,079 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views...
2022-09-16 10:30:44,080 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views: /tags/
2022-09-16 10:30:44,080 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) For the special root path /, don't scan /WEB-INF, /META-INF and /resources directories.
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views...
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views: /tags/tabscode.xhtml
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) scanView: / /tags/tabscode.xhtml = /tags/tabscode.xhtml
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) collectedExtensions: [*.xhtml]
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views: /primeflex/
2022-09-16 10:30:44,081 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) For the special root path /, don't scan /WEB-INF, /META-INF and /resources directories.
2022-09-16 10:30:44,083 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views...
2022-09-16 10:30:44,083 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) Scan Views: /primeflex/setup.xhtml
2022-09-16 10:30:44,083 INFO  [org.omn.fac.FacesViews] (Quarkus Main Thread) scanView: / /primeflex/setup.xhtml = /primeflex/setup.xhtml
```

**PROD:**
```
2022-09-16 10:27:57,393 INFO  [org.omn.ApplicationInitializer] (main) Using OmniFaces version 3.14-SNAPSHOT
2022-09-16 10:27:57,396 INFO  [org.omn.fac.FacesViews] (main) registerForwardingFilter
2022-09-16 10:27:57,396 INFO  [org.omn.fac.FacesViews] (main) First scan welcome files in web.xml
2022-09-16 10:27:57,478 INFO  [org.omn.fac.FacesViews] (main) Scan our dedicated directory for Faces resources that need to be mapped.
2022-09-16 10:27:57,480 INFO  [org.omn.fac.FacesViews] (main) scanAndStoreViews: true
2022-09-16 10:27:57,498 INFO  [org.omn.fac.FacesViews] (main) rootPath: /
2022-09-16 10:27:57,499 INFO  [org.omn.fac.FacesViews] (main) extension: .xhtml
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) resourcePaths is empty
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) rootPath: /WEB-INF/faces-views/
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) extension: null
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) resourcePaths is empty
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) rootPath: /META-INF/resources/
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) extension: .xhtml
2022-09-16 10:27:57,501 INFO  [org.omn.fac.FacesViews] (main) resourcePaths is empty
2022-09-16 10:27:57,502 INFO  [org.omn.fac.FacesViews] (main) collectedViews.keySet(): []
2022-09-16 10:27:57,502 INFO  [org.omn.fac.FacesViews] (main) excludedPaths: []
2022-09-16 10:27:57,502 INFO  [org.omn.fac.FacesViews] (main) collectedViews.isEmpty()
2022-09-16 10:27:57,502 INFO  [org.apa.myf.web.MyFacesContainerInitializer] (main) Using org.apache.myfaces.webapp.MyFacesContainerInitializer
```

**Comment by BalusC** [comment] 2022-09-16 17:23
https://github.com/omnifaces/omnifaces/commit/141f6305c649d60179e58c2bd53cb3a2411d0b64 fixed the welcome file part.

**Comment by melloware** [comment] 2022-09-16 21:30
I am going to try and write a small reproducer without OmniFaces to see if this is a Quarkus bug.

**Comment by melloware** [comment] 2022-09-17 11:55
Reproduced and reported to Quarkus.  Looks like a Quarkus Undertow bug.
https://github.com/quarkusio/quarkus/issues/28028

**Comment by BalusC** [comment] 2022-09-17 12:03
Okay, closing off then as the welcome file part is already fixed.

**Closed as completed by BalusC** 2022-09-17 12:03 UTC

**Comment by melloware** [comment] 2025-01-10 14:08
Thanks to @tandraschko this will be fixed in next MyFaces (https://issues.apache.org/jira/browse/MYFACES-4707) release so in Quarkus you can use...

```xml
    <context-param>
        <param-name>jakarta.faces.AUTOMATIC_EXTENSIONLESS_MAPPING</param-name>
        <param-value>true</param-value>
    </context-param>
```

You won't need to use the OmniFaces version of this.

**Comment by BalusC** [comment] 2025-01-10 14:25
> You won't need to use the OmniFaces version of this.

As long as you don't need MultiViews feature ;)

**Comment by melloware** [comment] 2025-01-10 14:37
ahhh yes 😄
