### ISSUE TITLE
ResetInputAjaxActionListener and Session already invalidated

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#878] opened 2024-11-04 19:19 UTC
I have some casual stack trace like that ...

what is better to do?:
1) a try catch inside OmniFaces `ResetInputAjaxActionListener`
2) add a catch `IllegalStateException` inside Mojarra `ActionListenerImpl`
3) ignore this kind of exceptions

```
java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:885)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:91)
	at org.jboss.weld.module.web.context.beanstore.http.AbstractSessionBeanStore.getAttribute(AbstractSessionBeanStore.java:102)
	at org.jboss.weld.contexts.beanstore.AttributeBeanStore.get(AttributeBeanStore.java:138)
	at org.jboss.weld.module.web.context.beanstore.http.AbstractSessionBeanStore.get(AbstractSessionBeanStore.java:87)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:83)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:115)
	at org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:78)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:192)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:706)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:139)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:164)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.parser.AstValue.getTarget(AstValue.java:73)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:221)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:230)
	at org.jboss.weld.module.web.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:40)
	at org.jboss.weld.module.web.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:70)
	at com.sun.faces.application.ActionListenerImpl.getNavigationOutcome(ActionListenerImpl.java:74)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:62)
	at org.omnifaces.eventlistener.ResetInputAjaxActionListener.processAction(ResetInputAjaxActionListener.java:196)
	at jakarta.faces.component.UIViewAction.broadcast(UIViewAction.java:506)
	at jakarta.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:868)
	at jakarta.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1348)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:56)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:689)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:185)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:142)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessIfNecessary(FacesViewsForwardingFilter.java:128)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:84)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1685)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1266)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:330)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:470)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:406)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by BalusC** [comment] 2024-11-05 19:22
The ResetInputAjaxActionListener doesn't do anything with the session. It's just delegating the action method call. Even with ResetInputAjaxActionListener removed it would still happen. It's the action method expression which apparently references a session scoped bean.

I only wonder why it didn't threw ViewExpiredException during restore view. Stateless view? If so why does it touch session scoped beans?

**Comment by pizzi80** [comment] 2024-11-06 10:29
thanks for your analysis!!

I'll investigate the situation with a catch on `ActionListenerImpl`
trying to detect the attribute and the component involved

... the views where these usually happens are for logged users so 
they are not transient and are backed by 
OmniFaces' `@ViewScoped` beans and other `@SessionScoped` beans ...

**Comment by BalusC** [comment] 2024-11-06 11:44
Not a stateless view? So it's a <f:viewAction> instead of a command button/link? I'm otherwise not seeing any reason why it didn't threw ViewExpiredException.

Or .. possibly the code is performing a logout (and invalidate session) at the wrong moment.

**Comment by pizzi80** [comment] 2024-11-08 19:16
> Not a stateless view? So it's a <f:viewAction> instead of a command button/link? I'm otherwise not seeing any reason> why it didn't threw ViewExpiredException.
> Or .. possibly the code is performing a logout (and invalidate session) at the wrong moment.

I've investigated both, was able to reproduce inside an `<f:viewAction`
introducing a `Thread.sleep` and manually destroying the session with tomcat manager
but in this case the stacktrace includes all the relevant information 
of the `f:viewAction` line of code that fails


After further investigation could be some jtstl `c:if` condition based on 
a session bean value .... 

I know that it should no be used but I've used it :D

I'll remove all those `c:if` and see what happens ...

**Comment by pizzi80** [comment] 2024-11-14 11:02
I added a catch `IllegalStateException` inside Mojarra `ActionListenerImpl`

After some days in production I found the issue:

As you said it's an `<f:viewAction action="#{bean.refresh}" />`

where the bean is `@SessionScoped`

don't know if it's a combination with a `<c:if` in the xhtml template

because in the stacktrace seems that's involved ...

```
java.lang.IllegalStateException: getAttribute: Session already invalidated
	at org.apache.catalina.session.StandardSession.getAttribute(StandardSession.java:885)
	at org.apache.catalina.session.StandardSessionFacade.getAttribute(StandardSessionFacade.java:91)
	at org.jboss.weld.module.web.context.beanstore.http.AbstractSessionBeanStore.getAttribute(AbstractSessionBeanStore.java:102)
	at org.jboss.weld.contexts.beanstore.AttributeBeanStore.get(AttributeBeanStore.java:138)
	at org.jboss.weld.module.web.context.beanstore.http.AbstractSessionBeanStore.get(AbstractSessionBeanStore.java:87)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:83)
	at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:115)
	at org.jboss.weld.contexts.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:78)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:192)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:706)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.module.web.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:139)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:164)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:134)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:152)
	at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
	at com.sun.faces.facelets.tag.TagAttributeImpl.getObject(TagAttributeImpl.java:289)
	at com.sun.faces.facelets.tag.TagAttributeImpl.getBoolean(TagAttributeImpl.java:107)
	at com.sun.faces.facelets.tag.jstl.core.IfHandler.apply(IfHandler.java:50)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:57)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:163)
	at com.sun.faces.facelets.tag.faces.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:177)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:139)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:57)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.applyNextHandler(DelegatingMetaTagHandler.java:163)
	at com.sun.faces.facelets.tag.faces.ComponentTagHandlerDelegateImpl.apply(ComponentTagHandlerDelegateImpl.java:177)
	at jakarta.faces.view.facelets.DelegatingMetaTagHandler.apply(DelegatingMetaTagHandler.java:139)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:57)
	at com.sun.faces.facelets.tag.faces.core.ViewHandler.apply(ViewHandler.java:172)
	at jakarta.faces.view.facelets.CompositeFaceletHandler.apply(CompositeFaceletHandler.java:57)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:52)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:46)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:265)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:318)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:301)
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:154)
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:129)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:52)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:46)
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:132)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:328)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:70)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:150)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:690)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:195)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.FacesExceptionFilter.doFilter(FacesExceptionFilter.java:118)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.filter.CacheControlFilter.doFilter(CacheControlFilter.java:239)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessToExtension(FacesViewsForwardingFilter.java:185)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLess(FacesViewsForwardingFilter.java:142)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.filterExtensionLessIfNecessary(FacesViewsForwardingFilter.java:128)
	at org.omnifaces.facesviews.FacesViewsForwardingFilter.doFilter(FacesViewsForwardingFilter.java:84)
	at org.omnifaces.filter.HttpFilter.doFilter(HttpFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:164)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:140)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344)
	at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:431)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.Nio2Endpoint$SocketProcessor.doRun(Nio2Endpoint.java:1685)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.net.AbstractEndpoint.processSocket(AbstractEndpoint.java:1266)
	at org.apache.tomcat.util.net.Nio2Endpoint.setSocketOptions(Nio2Endpoint.java:330)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:470)
	at org.apache.tomcat.util.net.Nio2Endpoint$Nio2Acceptor.completed(Nio2Endpoint.java:406)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker$2.run(Invoker.java:221)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1190)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1583)



```

**Comment by BalusC** [comment] 2024-11-14 14:55
c:if is not the cause.

Somewhere during the request the session was invalidated without that a redirect was performed. The correct practice is to send redirect immediately after invalidating a session so that JSF won't render the view.

Closing off as this is not an OmniFaces problem.

**Closed as completed by BalusC** 2024-11-14 14:55 UTC

**Comment by pizzi80** [comment] 2024-11-14 15:14
ok

seems like a Weld problem because I only call that method on an `<f:viewaction` 
and on an observer method on the same class ... 

Weld had also a similar bug (race condition) in the past ... 

thanks for your support!
