### ISSUE TITLE
[Enhancement] Allow definition of CDN resources depending on project stage

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#66] opened 2014-10-07 21:53 UTC
Allow definition of CDN resources depending on project stage since a more finer level of control would be a good enhancement.

*I do not know how this will influence #27*

## Idea: 

Use separate keys for each stage which overrides definition in default. This keeps backwards compatibility why allowing finer control.

    org.omnifaces.CDN_RESOURCE_HANDLER_URLS

    org.omnifaces.CDN_RESOURCE_HANDLER_URLS_PRODUCTION
    org.omnifaces.CDN_RESOURCE_HANDLER_URLS_DEVELOPMENT

## Use case:

These are mostly bundled resources within jar's. Such as `javax.faces:jsf.js` or any primefaces resources.

If static resources (js, css) are externalized to a CDN one want to disable certain CDN resources for quick **local** development/tests in case a new version should be used of the jar.

*This removes the need to comment it out always.*

## Example:

In production retrieve `jsf.js` from production CDN. While in development always use jar-bundled resource.

	<context-param>
		<param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
	<context-param>
	<context-param>
		<param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS_PRODUCTION</param-name>
		<param-value>javax.faces:jsf.js=www.cdn.de/production/jsf.js</param-value>
	<context-param>

**Comment by BalusC** [comment] 2015-03-02 15:51
Closing off as duplicate of #27.

**Closed by BalusC** 2015-03-02 15:51 UTC
