### ISSUE TITLE
o:validateBean throws NullPointerException if custom Hashcode/Equals implemented on objects

### ISSUE THREAD

**Issue by exabrial** [omnifaces/omnifaces#152] opened 2015-07-17 18:11 UTC
We use JPA, so we have `id` numbers for every object. If we override our hashcode/equals to use the id numbers, this causes `o:validateBean` to throw an NPE.

Fix was to add a null check in the reflection utils.

Here's the hashcode/equals:
```
	@Override
	public int hashCode() {
		if (id != null) {
			final int prime = 31;
			int result = 1;
			result = prime * result + ((id == null) ? 0 : id.hashCode());
			return result;
		} else {
			return super.hashCode();
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (id != null) {
			if (this == obj) {
				return true;
			}
			if (obj == null) {
				return false;
			}
			if (!(obj instanceof Identifiable)) {
				return false;
			}
			Identifiable other = (Identifiable) obj;
			if (id == null) {
				if (other.id != null) {
					return false;
				}
			} else if (!id.equals(other.id)) {
				return false;
			}
			return true;
		} else {
			return super.equals(obj);
		}
	}
```

Here's the stacktrace:
```
java.lang.NullPointerException
	at org.omnifaces.util.Reflection.setProperties(Reflection.java:71)
	at org.omnifaces.taghandler.ValidateBean$4.run(ValidateBean.java:308)
	at org.omnifaces.taghandler.ValidateBean$ValidateBeanCallback.invoke(ValidateBean.java:425)
	at org.omnifaces.util.Events$3.invoke(Events.java:351)
	at org.omnifaces.util.Events$7.afterPhase(Events.java:397)
	at org.omnifaces.eventlistener.CallbackPhaseListener.afterPhase(CallbackPhaseListener.java:70)
	at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersAfter(PhaseListenerManager.java:117)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:211)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.xxx.xxx.security.SecurityFilter.doFilter(SecurityFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by arjantijms** [comment] 2015-07-17 21:35
Can you provide some more information about what you're exactly trying to do with o:validateBean?

For normal usage of Reflection#setProperties the write method for each property MUST exist, so adding a null check there is perhaps not the right solution. It will now silently ignore cases where the write method does not exist, but for its intended purpose this should never happen.

The properties that are fed into Reflection#setProperties from ValidateBean originate from those discovered via validators attached to EditableValueHolders. If a property was found this way JSF has started to validate it, and thus will subsequently try to write to it. Your PR seems to suggest that in your case a property was detected that should be writable, but when it's time to indeed write to it, it's missing, and you like to ignore that fact?

Note that you can may be able to workaround your case by using a custom copier that returns a class (perhaps a DTO) that contains the writable property that's missing in your real class.

But I'm eager to learn what's exactly going on here, so additional information or a minimal reproducer would be appreciated. Thanks!

**Comment by exabrial** [comment] 2015-07-17 21:49
You can use an `EditableValueHolders` to display a read only value... For instance, you can display an inputField as readOnly be permanently disabling it. Your code can back this up by only providing a getter not a setter... Make sense?

I don't see how the patch is harmful though, because if a writer is not available, just simply don't set the value...

**Comment by arjantijms** [comment] 2015-07-17 22:21
>You can use an EditableValueHolders to display a read only value...

Of course, but if I'm not mistaken, JSF should not try to validate it in that case. The properties that are collected exclusively come from the validator, so a validation (on postback) must have been done.

So if you were binding `entity.id` to say `h:inputText` and set that to disabled, then upon a postback no validation should take place and hence no attempt to write to `entity.id` should be performed. I'll double check this assumption to be 100% sure though.

I'm also a bit puzzled how the hashCode/equals overrides that you mention in your openings post influences the apparently missing setter method for the `id` property.

>I don't see how the patch is harmful though, because if a writer is not available, just simply don't set the value...

The problem is that an exception should be thrown, since the Reflection#setProperties method is documented as setting all properties. If it silently ignores properties that don't exist, the caller should be aware of this since it may signal a problem elsewhere.

There's another method, Reflection#setPropertiesWithCoercion that can be used for cases where it doesn't matter that not all properties is set.

**Comment by exabrial** [comment] 2015-07-19 05:36
> The problem is that an exception should be thrown

Right, that makes sense I guess. So how do I proceed?

**Comment by exabrial** [comment] 2015-07-19 17:37
Well your suggestion works... I think the problem is that my Bean is Serializable, but `o:validateBean` makes the assumption that all fields are writable (Which _isn't_ a JavaBean requirement).

**Comment by arjantijms** [comment] 2015-07-20 11:21
Well, the best thing for us would to have a small reproducer for this, so we can actually see if and if so what is going wrong.

The problem is still that given the description it's difficult to do this. I discussed this with Bauke as well, and he couldn't quite make head or tails of the issue either.

You mentioned hashcode/equals in the openings post, but in all followup replies it didn't became quite clear how this relates to the issue at hand. Does the problem go away when you don't override hashcode/equals?

**Comment by exabrial** [comment] 2015-07-20 13:39
Yes, the problem is it exactly as I described... If you override the hash
code equals you get a NullPointerException. If you use the inherited
hashCode equals from the object superclass, the problem goes away. However
this breaks the behavior of sets and lists in our application.

**Comment by BalusC** [comment] 2015-07-20 14:55
I briefly looked at your equals() and it doesn't look right. Among others, you're only checking o==this when id is not null. This is indeed dangerous when you're collecting new entities in a list. 

I recommend rewriting your equals and hashCode according guidelines in http://stackoverflow.com/a/3181374/157882 and then retry the o:validateBean and retest the behavior in sets/lists.

**Comment by exabrial** [comment] 2015-07-20 15:11
So I decided to use the equals/hashcode generator in Eclipse:

```
@Override
    public int hashCode() {
            final int prime = 31;
            int result = 1;
            result = prime * result + ((id == null) ? 0 : id.hashCode());
            return result;
    }

    @Override
    public boolean equals(Object obj) {
            if (this == obj) {
                return true;
            }
            if (obj == null) {
                return false;
            }
            if (!(obj instanceof Identifiable)) {
                return false;
            }
            Identifiable other = (Identifiable) obj;
            if (id == null) {
                if (other.id != null) {
                    return false;
                }
            } else if (!id.equals(other.id)) {
                return false;
            }
            return true;
    }
```

Same result:

```
java.lang.NullPointerException
	at org.omnifaces.taghandler.ValidateBean$6.invoke(ValidateBean.java:333)
	at org.omnifaces.taghandler.ValidateBean$6.invoke(ValidateBean.java:326)
	at org.omnifaces.util.Components$ForEach$1.visit(Components.java:492)
	at org.omnifaces.util.Components$ForEach$TypesVisitCallback.visit(Components.java:557)
	at org.apache.myfaces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:141)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
```

**Comment by exabrial** [comment] 2015-07-20 15:14
Used the suggested HashCode/Equals VERBATIM with the same result:

```

	@Override
	public boolean equals(Object object) {
		return (object instanceof Identifiable) && (id != null) ? id.equals(((Identifiable) object).id) : (object == this);
	}

	@Override
	public int hashCode() {
		return (id != null) ? (Identifiable.class.hashCode() + id.hashCode()) : super.hashCode();
	}
```


```
java.lang.NullPointerException
	at org.omnifaces.taghandler.ValidateBean$6.invoke(ValidateBean.java:333)
	at org.omnifaces.taghandler.ValidateBean$6.invoke(ValidateBean.java:326)
	at org.omnifaces.util.Components$ForEach$1.visit(Components.java:492)
	at org.omnifaces.util.Components$ForEach$TypesVisitCallback.visit(Components.java:557)
	at org.apache.myfaces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:141)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1016)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIComponent.visitTree(UIComponent.java:1044)
	at javax.faces.component.UIComponentBase.visitTree(UIComponentBase.java:1191)
	at javax.faces.component.UIForm.visitTree(UIForm.java:345)
	at org.omnifaces.util.Components$ForEach.invoke(Components.java:525)
	at org.omnifaces.util.Components$ForEach.invoke(Components.java:489)
	at org.omnifaces.taghandler.ValidateBean.forEachInputWithMatchingBase(ValidateBean.java:326)
	at org.omnifaces.taghandler.ValidateBean.access$400(ValidateBean.java:151)
	at org.omnifaces.taghandler.ValidateBean$3.run(ValidateBean.java:286)
	at org.omnifaces.taghandler.ValidateBean$ValidateBeanCallback.invoke(ValidateBean.java:430)
	at org.omnifaces.util.Events$3.invoke(Events.java:351)
	at org.omnifaces.util.Events$6.beforePhase(Events.java:385)
	at org.omnifaces.eventlistener.CallbackPhaseListener.beforePhase(CallbackPhaseListener.java:63)
	at org.apache.myfaces.lifecycle.PhaseListenerManager.informPhaseListenersBefore(PhaseListenerManager.java:77)
	at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:184)
	at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:143)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:205)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
	at org.ocpsoft.rewrite.servlet.impl.HttpRewriteResultHandler.handleResult(HttpRewriteResultHandler.java:41)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.rewrite(RewriteFilter.java:268)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:188)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.springventuregroup.shpyard.security.SecurityFilter.doFilter(SecurityFilter.java:79)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:318)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BalusC** [comment] 2015-07-20 15:28
It should at least fix the behavior as described in "this breaks the behavior of sets and lists in our application". 

Not sure about the NullPointerException in o:validateBean. A reproducer would be really helpful.

**Comment by exabrial** [comment] 2015-07-20 15:30
If I take the time to create a reproducer do you swear you'll actually
apply this patch? I feel like I'm chasing a moving target now.

**Comment by BalusC** [comment] 2015-08-30 20:00
As to the reproducer, the proposed patch doesn't look like the right way as this problem should theoretically never occur based on the information provided so far. This feels too much like a XY problem. With a reproducer we can investigate on our own how exactly the problem is caused. If the problem is after all indeed caused by OmniFaces, then we'll of course fix it. We only don't promise (or "swear") to apply exactly your patch as the solution.

This is not to act like a moving target, but to find the right solution for the actual problem. We don't like having localized workarounds in OmniFaces, but real solutions.

I hope you understand this.

**Comment by exabrial** [comment] 2015-08-31 17:08
I understand, sorry for being uppitty.

**Comment by BalusC** [comment] 2015-11-26 10:18
Closing off as no-repro.

If you've a reproducer, please open a new issue.

**Closed by BalusC** 2015-11-26 10:18 UTC
