### ISSUE TITLE
problem with <f:websocket> Java EE 8 in Payara 5.193

### ISSUE THREAD

**Issue by avbravo** [omnifaces/omnifaces#525] opened 2019-09-25 03:57 UTC
When I use websocket with PayaraMicro 5.193
Java Enterprise Edition 8

```
<dependency>
            <groupId>javax.websocket</groupId>
            <artifactId>javax.websocket-api</artifactId>
            <version>1.1</version>
            <scope>provided</scope>
        </dependency>
<dependency>
            <groupId>org.omnifaces</groupId>
            <artifactId>omnifaces</artifactId>
            <version>3.3</version>
            <type>jar</type>
        </dependency>
```

just adding the omnifaces library generates the error

[2019-09-24T22:50:44.133-0500] [] [ADVERTENCIA] [NCLS-CORE-00069] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1569383444133] [levelValue: 900] [[
  Exception while dispatching an event
java.lang.IllegalStateException: Node failed to start!
	at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:138)
	at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:228)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:207)
	at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:157)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:506)
	at fish.payara.nucleus.hazelcast.HazelcastCore.getInstance(HazelcastCore.java:271)
	at fish.payara.nucleus.store.ClusteredStore.get(ClusteredStore.java:182)
	at fish.payara.nucleus.microprofile.config.source.ClusterConfigSource.getValue(ClusterConfigSource.java:80)

**Comment by BalusC** [comment] 2019-12-30 11:29
No clue how to reproduce.

Please add detailed instructions.

**Comment by adam-waldenberg** [comment] 2020-05-04 17:42
This looks like a Hazelcast issue - Are you sure it's related to o/f:socket/webSocket? I have seen it under other siutations.

**Comment by melloware** [comment] 2020-12-05 19:05
I think this issue can be closed as the OP has not responded and it does seem like a Hazelcast issue.

**Comment by adam-waldenberg** [comment] 2020-12-06 07:18
@melloware It is a hazelcast issue - and it's related to the way Hazelcast is initialized in later versions. However, personally I have only seen it when for example running either multiple instances of  Payara in combination with for example the embedded container. OP does not specify his setup - so it's hard to guess if its the same thing.

**Comment by adam-waldenberg** [comment] 2020-12-06 07:21
FYI my solution has always been to downgrade to  5.181 which has an older Hazelcast that initializes differently. So you could try and see if that solves it @avbravo.

**Comment by BalusC** [comment] 2020-12-06 10:20
Okay, closing off as not an OmniFaces problem.

If this can however be solved with a code change / patch in OmniFaces side, then please reopen along with a PR / reproducer.

**Closed by BalusC** 2020-12-06 10:20 UTC
