### ISSUE TITLE
blank page after reopening a @ViewScoped page after invalidateSession()

### ISSUE THREAD

**Issue by danteCarvalho** [omnifaces/omnifaces#690] opened 2022-05-16 05:21 UTC
If i am on a @ViewScoped page and i  do invalidateSession(), and redirect to another page it works as normal, but the first time i go back to that page the page is always blank. If i refresh the page it works again.

I am using ominifaces 2.7.15

**Comment by BalusC** [comment] 2022-05-16 09:52
Sounds like it's gone wrong in the browser cache. 

Have you installed the `CacheControlFilter` (https://showcase.omnifaces.org/filters/CacheControlFilter)? You need minimally the `noCache` configuration example.

**Comment by danteCarvalho** [comment] 2022-05-16 23:57
I put the noCache configuration, but still got the blank page.
i also updated to version 2.7.18
I am using the Jboss EAP 7.0.0
Java 8

web.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<web-app
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
	id="WebApp_ID"
	version="3.1"
>
	<display-name>TechBox</display-name>
	<welcome-file-list>
		<welcome-file>login.xhtml</welcome-file>
	</welcome-file-list>
	<context-param>
		<param-name>javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL</param-name>
		<param-value>true</param-value>
	</context-param>
	<context-param>
		<param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
		<param-value>/*.xhtml</param-value>
	</context-param>
	<context-param>
		<param-name>org.omnifaces.SOCKET_ENDPOINT_ENABLED</param-name>
		<param-value>true</param-value>
	</context-param>
	<context-param>
		<param-name>javax.faces.DATETIMECONVERTER_DEFAULT_TIMEZONE_IS_SYSTEM_TIMEZONE</param-name>
		<param-value>true</param-value>
	</context-param>
	<session-config>
		<session-timeout>60</session-timeout>
		<tracking-mode>COOKIE</tracking-mode>
	</session-config>
	<login-config>
		<auth-method>FORM</auth-method>
		<form-login-config>
			<form-login-page>/login.xhtml</form-login-page>
			<form-error-page>/login.xhtml</form-error-page>
		</form-login-config>
	</login-config>
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>login</web-resource-name>
			<url-pattern>/sistema/*</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>*</role-name>
		</auth-constraint>
		<user-data-constraint>
			<transport-guarantee>NONE</transport-guarantee>
		</user-data-constraint>
	</security-constraint>
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>login</web-resource-name>
			<url-pattern>/sistema/admin/*</url-pattern>
		</web-resource-collection>
		<auth-constraint>
			<role-name>AGENTECH</role-name>
		</auth-constraint>
		<user-data-constraint>
			<transport-guarantee>NONE</transport-guarantee>
		</user-data-constraint>
	</security-constraint>
	<security-role>
		<role-name>ADMINISTRADOR</role-name>
	</security-role>
	<security-role>
		<role-name>AGENTECH</role-name>
	</security-role>
	<security-role>
		<role-name>USUARIO</role-name>
	</security-role>
	<servlet>
		<servlet-name>Faces Servlet</servlet-name>
		<servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
		<load-on-startup>1</load-on-startup>
	</servlet>
	<servlet-mapping>
		<servlet-name>Faces Servlet</servlet-name>
		<url-pattern>*.xhtml</url-pattern>
	</servlet-mapping>
	<filter>
		<filter-name>noCache</filter-name>
		<filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
	</filter>
	<filter-mapping>
		<filter-name>noCache</filter-name>
		<url-pattern>/*</url-pattern>
	</filter-mapping>
</web-app>
```

faces-config.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<faces-config xmlns="http://xmlns.jcp.org/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-facesconfig_2_3.xsd"
	version="2.3">
	<factory>
		<exception-handler-factory>org.omnifaces.exceptionhandler.FullAjaxExceptionHandlerFactory</exception-handler-factory>
	</factory>
	<factory>
		<exception-handler-factory>
			br.com.techbox.local.CustomExceptionHandlerFactory
		</exception-handler-factory>
	</factory>
</faces-config>

```
the invalidateSession method
```java
public void logout() throws Exception {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		String contextPath = FacesContext.getCurrentInstance().getExternalContext().getRequestContextPath();
                FacesContext.getCurrentInstance().getExternalContext().redirect(contextPath + + "/login.xhtml");
}
```
index.xhml -> invalidateSession ->  redirect -> login.xhtml
![Screenshot from 2022-05-16 20-54-08](https://user-images.githubusercontent.com/6034345/168700588-be7d9612-57d0-4c2d-81f1-86f072bd8890.png)


login.xhtml -> redirect -> index.xhtml
![Screenshot from 2022-05-16 20-26-20](https://user-images.githubusercontent.com/6034345/168698267-b556ce76-6bba-4530-8b77-6bc252c785e0.png)

**Comment by danteCarvalho** [comment] 2022-05-17 00:22
I just tryed to put a conditional breakpoint  on the isUnloadRequest 

"unload".equals(getRequestParameter(context, "omnifaces.event")) == true

```java
public static boolean isUnloadRequest(FacesContext context) {
		return "unload".equals(getRequestParameter(context, "omnifaces.event"));
	}
```
but the breakpoint does not stop when the invalidatesession() is called

**Comment by melloware** [comment] 2022-05-17 00:52
If you are using jboss 7 eap don't you need OmniFaces 3 not 2?

I use EAP 7 also and it's later JSF and CDI so you need OmniFaces 3.13.2

**Comment by danteCarvalho** [comment] 2022-05-17 01:55
If i start the project with omnifaces 2 the deploy works
Processing weld deployment TesteWeb.war
16/05 22:52:20,249 [INFO] [org.jboss.weld.deployer] WFLYWELD0006: Starting Services for CDI deployment: TesteWeb.war
16/05 22:52:20,256 [INFO] [org.jboss.weld.deployer] WFLYWELD0009: Starting weld service for deployment TesteWeb.war
16/05 22:52:22,241 [INFO] [org.omnifaces.ApplicationInitializer] Using OmniFaces version 2.7.18
16/05 22:52:22,505 [INFO] [javax.enterprise.resource.webcontainer.jsf.config] Initializing Mojarra 2.2.12-jbossorg-2  for context '/TesteWeb'
16/05 22:52:22,941 [INFO] [org.wildfly.extension.undertow] WFLYUT0021: Registered web context: /TesteWeb
16/05 22:52:22,977 [INFO] [org.jboss.as.server] WFLYSRV0010: Deployed "TesteWeb.war" (runtime-name : "TesteWeb.war")

but with omnifaces 3 the deploy does not work

16/05 22:54:23,613 [INFO] [org.jboss.weld.deployer] WFLYWELD0003: Processing weld deployment TesteWeb.war
16/05 22:54:23,743 [INFO] [org.jboss.weld.deployer] WFLYWELD0006: Starting Services for CDI deployment: TesteWeb.war
16/05 22:54:23,760 [INFO] [org.jboss.weld.deployer] WFLYWELD0009: Starting weld service for deployment TesteWeb.war
16/05 22:54:23,995 [WARN] [org.jboss.modules] Failed to define class org.omnifaces.component.search.MessagesKeywordResolver in Module "deployment.TesteWeb.war:main" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link org/omnifaces/component/search/MessagesKeywordResolver (Module "deployment.TesteWeb.war:main" from Service Module Loader): javax/faces/component/search/SearchKeywordResolver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:446)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
	at org.jboss.modules.Module.loadModuleClass(Module.java:605)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
	at org.jboss.as.weld.WeldModuleResourceLoader.classForName(WeldModuleResourceLoader.java:68)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadClass(AnnotatedTypeLoader.java:65)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:60)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:96)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:97)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:65)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

16/05 22:54:24,003 [INFO] [org.jboss.weld.Bootstrap] WELD-000119: Not generating any bean definitions from org.omnifaces.component.search.MessagesKeywordResolver because of underlying class loading error: Type Failed to link org.omnifaces.component.search.MessagesKeywordResolver (Module "deployment.TesteWeb.war:main" from Service Module Loader): javax.faces.component.search.SearchKeywordResolver not found.  If this is unexpected, enable DEBUG logging to see the full error.
16/05 22:54:24,059 [ERROR] [org.jboss.msc.service.fail] MSC000001: Failed to start service jboss.deployment.unit."TesteWeb.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."TesteWeb.war".WeldStartService: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.reflect.MalformedParameterizedTypeException
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:58)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:51)
	at sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:92)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.<init>(BackedAnnotatedMethod.java:38)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedMethod.of(BackedAnnotatedMethod.java:32)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:195)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.computeValue(BackedAnnotatedType.java:188)
	at org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:35)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$EagerlyInitializedLazyValueHolder.<init>(BackedAnnotatedType.java:156)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:188)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType$BackedAnnotatedMethods.<init>(BackedAnnotatedType.java:188)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.<init>(BackedAnnotatedType.java:63)
	at org.jboss.weld.annotated.slim.backed.BackedAnnotatedType.of(BackedAnnotatedType.java:44)
	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.load(ClassTransformer.java:83)
	at org.jboss.weld.resources.ClassTransformer$TransformClassToBackedAnnotatedType.load(ClassTransformer.java:80)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCacheValue(LoadingCacheUtils.java:49)
	at org.jboss.weld.util.cache.LoadingCacheUtils.getCastCacheValue(LoadingCacheUtils.java:74)
	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:175)
	at org.jboss.weld.resources.ClassTransformer.getBackedAnnotatedType(ClassTransformer.java:194)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:113)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.createContext(FastAnnotatedTypeLoader.java:102)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:91)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:97)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:65)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:63)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

16/05 22:54:24,067 [ERROR] [org.jboss.as.controller.management-operation] WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "TesteWeb.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"TesteWeb.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"TesteWeb.war\".WeldStartService: Failed to start service
    Caused by: java.lang.reflect.MalformedParameterizedTypeException"}}
16/05 22:54:24,088 [INFO] [org.jboss.as.server] WFLYSRV0010: Deployed "TesteWeb.war" (runtime-name : "TesteWeb.war")
16/05 22:54:24,088 [INFO] [org.jboss.as.controller] WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."TesteWeb.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."TesteWeb.war".WeldStartService: Failed to start service

**Comment by melloware** [comment] 2022-05-17 11:36
OK then Jboss EE 7 must be EE7 still not EE8.  I am using Jboss 7.3 and Jboss 7.4 and definitely need OmniFaces 3.

**Comment by BalusC** [comment] 2022-12-10 10:25
> I just tryed to put a conditional breakpoint on the isUnloadRequest
> 
> `"unload".equals(getRequestParameter(context, "omnifaces.event")) == true`
> 
> but the breakpoint does not stop when the invalidatesession() is called

Indeed, this is the problem. The unload request is being 301-redirected to the login page according to [this screenshot](https://user-images.githubusercontent.com/6034345/168700588-be7d9612-57d0-4c2d-81f1-86f072bd8890.png).

Technically speaking, the security framework being used must skip unload requests.

I can unfortunately not answer this off top of head for JBoss EAP 7, but I do remember that a former project used "[OmniSecurity](https://github.com/omnifaces/omnisecurity)" (the predecesor of JSR375) in combination with [this patch](https://github.com/omnifaces/omnisecurity-cdi-auth-events-undertow) for a Java EE 7 version of WildFly. You basically need to install a custom auth handler which manually checks `ViewScopeManager#isUnloadRequest()` before continuing.

@arjantijms do you perhaps have a concrete example at hands?

**Comment by BalusC** [comment] 2023-02-10 11:11
Closing off, not a bug.

**Closed as completed by BalusC** 2023-02-10 11:11 UTC
