### ISSUE TITLE
Conversation ID of @ConversationScoped lacks

### ISSUE THREAD

**Issue by ahamana** [omnifaces/omnifaces#455] opened 2018-04-13 14:57 UTC
In the OmniFaces 2.6.9, when the @ConversationScoped bean execute the Faces#navigate twice or more, the conversation ID(cid) lacks on the view.
e.g.) 
http\://localhost/flow1 (Initialize the conversation scope.)
Faces#navigate -> http\://localhost/flow2?cid=1
Faces#navigate -> http\://localhost/flow3

\* In the OmniFaces 2.6.8, the conversation ID does not lack.

[My code]
```
package test;

import java.io.Serializable;

import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.omnifaces.util.Faces;

@ConversationScoped
@Named
@SuppressWarnings("serial")
public class TestFlow implements Serializable
{
    @Inject
    private Conversation conversation;

    public void initConversation()
    {
        if ( conversation.isTransient() ) {
            conversation.begin();
        }
    }

    public void moveToFlow2()
    {
        // Do something.

        Faces.navigate( "/flow2" );
    }

    public void moveToFlow3()
    {
        // Do something.

        Faces.navigate( "/flow3" );
    }

    public void cancel()
    {
        conversation.end();

        Faces.navigate( "/index" );
    }
}
```

## Environment ##
- **Omnifaces Version**: 2.6.9
- **JDK Version**: 8 u162 - Oracle

**Comment by BalusC** [comment] 2018-04-14 08:44
Are you using FacesViews feature?

**Comment by ahamana** [comment] 2018-04-14 16:44
@BalusC  Yes, I use FacesViews / ExtensionlessURLs feature.

**Comment by BalusC** [comment] 2018-04-14 17:42
Cannot reproduce your problem. It works for me exactly as you described, and the behavior is the same in 2.6.8 / 2.6.9 / 3.0 / 3.1.

What's the value of `org.omnifaces.FACES_VIEWS_SCAN_PATHS`? I used the minimal configuration of `/*.xhtml` and I tested on WildFly 12 with Mojarra 2.3.4. Can you create a reproducer project?

**Comment by ahamana** [comment] 2018-04-15 09:43
I have created a reproducer project.
[test.zip](https://drive.google.com/file/d/1ZF4fUgA9IqTF19SASKafBaKRfNnRkMUD/view?usp=sharing)

1\. http://xxx/(context-path)/flow1 (click the "Flow2" button)
2\. http://xxx/(context-path)/flow2 (click the "Flow3" button)
3\. http://xxx/(context-path)/flow3
\* In case of 2.6.8, the flow3 view is displayed, but in case of 2.6.9, the flow3 view is not found because conversation ID lacks.

note: 
 \- this project is an Eclipse Gradle project.
 \- I test on [Payara 4.1.2.174](https://s3-eu-west-1.amazonaws.com/payara.fish/Payara+Downloads/Payara+4.1.2.174/payara-ml-4.1.2.174.zip) with Mojarra 2.2.14(-SNAPSHOT 20170628-1326.
 \- I test through a web server(Apache).

**Comment by BalusC** [comment] 2018-04-15 19:05
Reproduced it. This is a regression of https://github.com/omnifaces/omnifaces/issues/449. I have accidentally committed a part of the fix into 3.1 instead of 2.6.9. I'll have to cherrypick the fixes back into 2.x.

It works when I move out the files in `/WEB-INF/faces-views` into `/`. This is your work-around for now.

**Comment by BalusC** [comment] 2018-04-15 19:30
Please give [2.6.10-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.6.10-SNAPSHOT/) a try. It should fix your issue.

**Comment by BalusC** [comment] 2018-04-16 11:59
Great!

Thank you for reporting the issue :)

**Closed by BalusC** 2018-04-16 11:59 UTC
