### ISSUE TITLE
o:messages occasionally stops working

### ISSUE THREAD

**Issue by bobbotron** [omnifaces/omnifaces#324] opened 2016-11-03 18:29 UTC
Hi there.  My apologies if this turns out to not be an omnifaces bug but I thought you fine folks might give me some pointers for debugging this issue.

I have a web application where I'm using one Omnifaces o:messages tag to display messages near the top of the a JSF page template.  The structure of the page is roughly below (I've removed a lot of code to simplify things.)

```
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:o="http://omnifaces.org/ui"
    xmlns:of="http://omnifaces.org/functions"
    xmlns:comp="http://java.sun.com/jsf/composite/composites">
<h:head>
</h:head>
<h:body >
<div class="main-section">
<ui:insert name="content-section" />
</div>
<h:panelGroup id="messages">
            <o:messages var="message">
<p>Message #{of:escapeJS(message.summary)}</p>
</o:messages>
</h:panelGroup>
</h:body>
</html>
```

And then in various AJAX updates, I reference this messages section like so:

```
<h:commandButton actionListener="#{aBean.action()}">
<f:ajax render="@form :messages" />
</h:commandButton>

```

This works, and is quite nice in my case, but sometimes on application (server?) load this o:messages section produces one message with all fields blank on page load, and then on any AJAX refresh no messages, even if messages are registered.  This behaviour persists until the application is unloaded and redeployed.  At this point I can't figure out exactly how to reproduce, but it happens fairly often.  That I know of, no pertinent errors are logged to server.log, but I might be overlooking them.

 Any ideas where I should start looking?  This is with Glassfish 4.1.1, Mojarra 2.2.12, WELD 2.2.13 (Final) and Omnifaces 2.5.1, I can find other library versions if that would help.

Thanks!

**Comment by BalusC** [comment] 2016-11-07 08:55
Sounds like the component tree is not thread safe, e.g. by binding a component to a non-request scoped bean. To exclude that from being the cause, set in web.xml

```
<context-param>
    <param-name>javax.faces.SERIALIZE_SERVER_STATE</param-name>
    <param-value>true</param-value>
</context-param>
```

This will throw serialization exceptions when the component tree is indeed not thread safe. The exception in turn should give clues about the root mistake.

**Comment by bobbotron** [comment] 2016-11-11 14:57
Hi Bauke.  Thanks - I've added this to my project.  The bug manifested again, I didn't see any exception thrown in the server.log glassfish log files.  Very curious!

**Comment by bobbotron** [comment] 2016-11-18 16:53
While I've long since learned to never say never, I just confirmed this is occurring on pages that don't use any binding.  We only use binding in about two places in the app, everywhere else is backing beans properties.

**Comment by bobbotron** [comment] 2016-11-18 19:40
Here's a pretty basic page that I wrote to reproduce.  The idea is that a toastr JS alert message is displayed for each message.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:o="http://omnifaces.org/ui"
	xmlns:of="http://omnifaces.org/functions"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Blank</title>
</h:head>
<h:body bgcolor="white">
	<p>Messages</p>
	<o:messages var="message">
		<script type="text/javascript">
				/*
				severity #{message.severity}
		        detail #{message.detail}
		        summary #{message.summary}
		        	*/
		        	var severity = '#{message.severity.ordinal}';
		        	var message = '#{of:escapeJS(message.summary)}';
		        	
		        	if (message !== '') {
			        	switch (severity) {
				        	case '0':
				        		toastr.info(message);
				        		break;
				        	case '1':
				        		toastr.warning(message);
				        		break;
			        		default:
			        	 		toastr.error(message);
			        			break;
			        	}
		        	}
		        	else {
		        		toastr.warning('Warning, error messages are currently disabled');
		        	}
				</script>
	</o:messages>
</h:body>
</html>
```

Which, when the bug is manifesting itself, generates this HTML:

```
<html xmlns="http://www.w3.org/1999/xhtml"><head id="j_idt2">
	<title>Blank</title></head><body>
	<p>Messages</p>
		<script type="text/javascript">
				/*
				severity 
		        detail 
		        summary 
		        	*/
		        	var severity = '';
		        	var message = '';
		        	var displayMessage = true;
		        	
		        	if (message !== '') {
			        	switch (severity) {
				        	case '0':
				        		toastr.info(message);
				        		break;
				        	case '1':
				        		toastr.warning(message);
				        		break;
			        		default:
			        	 		toastr.error(message);
			        			break;
			        	}
		        	}
		        	else if ( displayMessage ) {
		        		toastr.warning('Warning, error messages are currently disabled');
		        	}
				</script>
</body></html>
```

**Comment by BalusC** [comment] 2016-11-25 13:16
That code only demonstrates what (theoretically) happens when the bug manifests, but it unfortunately doesn't reproduce the bug itself.

We are using `<o:messages>` in production environments for years and I've never seen this issue before. 

The only thing which caught my eye in those snippets is that you're rendering global script variables. Chances are that in your real code those variables are being rendered multiple times into same document and thus overriding each other. I recommend to wrap the entire script body in a closure (self-executing anonymous function) and retry.

```
<script>
    (function() {
        // Original script code here.
    })();
</script>

**Comment by bobbotron** [comment] 2016-12-07 19:27
Hey @BalusC, I'll give this a shot, that's totally fair and definitely cleaner JS that we should be committing to regardless.  

For this issue, I'm reasonably sure that this isn't the cause of our problems with h:messages.  When the error occurs, no real messages are rendered by the h:messages tag either on page load on on ajax callbacks.  This can be double checked by using an inspector and looking at the rendered HTML in browser.  

I'll keep investigating, I'll let you know if I figure anything more out on this.

I've just reproduced this locally on my laptop, using the following:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html">

<h:head>
	<title>Healthcheck</title>
</h:head>
<h:body bgcolor="white">
	<dl>
		<dt>Version</dt>
		<dd>#{appVersion.version}</dd>
		<dt>Database Health</dt>
		<dd>#{dbHealth.dbOk ? 'Up' : 'Down' }</dd>
		<dt>Environment</dt>
		<dd>#{properties.get('env') }</dd>

		<h:messages var="message">
			<dt>Message</dt>
			<dd>'#{message.summary}'</dd>
		</h:messages>
	</dl>
</h:body>
</html>
```

Which results in the following.  Note there is no Javascript here.

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="j_idt2">
<body>
<dl>
<dt>Version</dt>
<dd>1.0.11</dd>
<dt>Database Health</dt>
<dd>Up</dd>
<dt>Environment</dt>
<dd>local</dd>
<dt>Message</dt>
<dd>''</dd>
</dl>
</body>
</html>
```

**Comment by BalusC** [comment] 2016-12-07 20:37
Didn't you mean to use `<o:messages>`?

**Comment by bobbotron** [comment] 2016-12-07 20:43
Ack, you are correct, sorry about that.  I am using `<o:messages>` on my main template, used the wrong one on this test page.  The problem has gone away, I'll double check with this if/when it reoccurs.

**Comment by bobbotron** [comment] 2016-12-13 19:28
I've decided to loop over the list of messages coming from the faces context instead, this seems to be working well in my case.

`<ui:repeat var="message" value="#{facesContext.messageList}">`

**Comment by BalusC** [comment] 2016-12-18 22:00
Closing off as no-repro. Please open a new issue if you have a reproducer.

**Closed by BalusC** 2016-12-18 22:00 UTC
