### ISSUE TITLE
Tooltip's not rendered after defer primefaces

### ISSUE THREAD

**Issue by MSzturc** [omnifaces/omnifaces#88] opened 2015-01-06 16:11 UTC
When initialize primefaces through deferredScript as described on [Stackoverflow](http://stackoverflow.com/a/23173640) tooltips are not longer working.

Example:

```
<?xml version='1.0' encoding='UTF-8' ?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:pe="http://primefaces.org/ui/extensions"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <h:head>
        <meta name="viewport" content="initial-scale=1.0"/>
        <h:outputScript library="js" name="primefaces.deferred.js" target="head" />

        <o:deferredScript library="primefaces" name="jquery/jquery-plugins.js" />
        <o:deferredScript library="primefaces" name="primefaces.js" onbegin="DeferredPrimeFaces.begin()" />
        <o:deferredScript library="primefaces" name="layout/layout.js" />
        <o:deferredScript library="primefaces" name="watermark/watermark.js" />
        <o:deferredScript library="primefaces" name="fileupload/fileupload.js" onsuccess="DeferredPrimeFaces.apply()" />
        <o:deferredScript library="omnifaces" name="fixviewstate.js" />
    </h:head>

    <h:body>
        <h:form id="form" >
            <p:inputText id="xx" required="true"/>
            <h:commandButton id="submit" value="submit" />
            <p:tooltip id="tooltip" for="xx" value="Tooltip" />
        </h:form>
    </h:body>
</html>
```

Tested on:
Mojarra 2.2.7 OmniFaces 2.0 PrimeFaces 5.1 GlassFish Server Open Source Edition 4.1 

The JavaScript console says:
Uncaught ReferenceError: DeferredPrimeFaces is not defined

**Comment by MSzturc** [comment] 2015-01-06 16:48
After a bit of debugging i found out that the CombinedResourceHandler causes this problem.
After removing the target from primefaces.deferred.js tooltips are workings as they should.

```
<h:outputScript library="js" name="primefaces.deferred.js" />
```

**Comment by MSzturc** [comment] 2015-01-06 17:13
Closed too early, the problem still occures on validation messages rendered as tooltip.

Example:

```
<h:body>
        <h:form>
            <p:inputText id="xx" required="true"/>
            <h:commandButton id="submit" value="submit" />
            <p:message id="msg" for="xx" display="tooltip" />
        </h:form>
    </h:body>
```

**Comment by BalusC** [comment] 2015-01-08 08:10
Hmm, works just fine for me. What exactly is being combined in the combined script resource in the head? What's the combined resource URL? When I take over your example, I get http://localhost:8088/playground/javax.faces.resource/eNrLz83LTEtMTi22yoex9LKKawqKMnNTIbyU1LTUoqLUFFRhq6zC0tSiSn0IBZQDADU3HRQ.js.xhtml?ln=omnifaces.combined&v=1419938518000 which contains omnifaces:omnifaces.js, primefaces.deferred.js (I didn't put it in a library) and primefaces:jquery/jquery.js.

**Comment by BalusC** [comment] 2015-03-02 14:15
Any feedback?

**Comment by BalusC** [comment] 2015-07-13 18:33
Can't reproduce and no feedback, so closing out.

**Closed by BalusC** 2015-07-13 18:33 UTC

**Comment by jlerbsc** [comment] 2016-09-13 15:11
Hi Balusc,
I have exactly the same issue if i use CombinedResourceHandler with deferredScript.
I'm using the same exemple (copy/paste)and i get :
Uncaught ReferenceError: PrimeFaces is not defined
Uncaught ReferenceError: DeferredPrimeFaces is not defined
with primefaces 5.3.25 and omnifaces 1.11
