### ISSUE TITLE
CombinedResourceHander script odering

### ISSUE THREAD

**Issue by smasala** [omnifaces/omnifaces#37] opened 2014-05-28 09:37 UTC
Is it possible to set the order of the scripts with the CRH?

For example RichFaces has its own jQuery library. I can't map the jQuery file to version 2.x because RichFaces uses deprecated (now removed) functions.

If I could get my jQuery library (2.1.1) combined before RichFaces, I could then map the RichFaces jQuery library using the RichFaces ```static-resource-mappings.properties``` file to the jQuery migrate plugin instead. That way, I can get the benefit of jQuery 2.x and still allow RichFaces outdated functions to work.

I know with omnifaces you allow custom attributes. Perhaps this may be a possiblity? Or over a context-param?

Thanks in advance

**Comment by BalusC** [comment] 2015-01-03 00:11
OmniFaces 2.0 contained some fixes wrt RichFaces 4.5 resources as per #63. 

Can you retry?

**Comment by BalusC** [comment] 2015-03-02 16:32
Can't reproduce with OmniFaces 2.1 SNAPSHOT + RichFaces 4.5.2 + MyFaces 2.2.6 (2.2.7 didn't work, it threw IOOBE at FacesConfigurator#getLastMofidiedTime() on every request). 

Closing off as no-repro. Feel free to open new one if you still stumble upon this problem with mentioned versions or newer.

**Closed by BalusC** 2015-03-02 16:32 UTC
