### ISSUE TITLE
NPE in EagerBeansWebListener

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#638] opened 2021-08-19 12:36 UTC
I am trying to create a small application demonstrating PFE components that show your WIKI CombinedResourceHandler: https://github.com/omnifaces/omnifaces/wiki/Combine-hardcoded-PrimeFaces-resources-using-CombinedResourceHandler however I am getting an NPE and can't figure out why?

**OmniFaces** 3.11.1
**PrimeFaces** 10.0.0
**MyFaces** 2.3
**OpenWebBeans** 2.0.23

Reproducer: 
[pfe-combinedresourcehandler.zip](https://github.com/omnifaces/omnifaces/files/7014365/pfe-combinedresourcehandler.zip)

Run `mvn clean jetty:run -Pmyfaces23` and navigate to http://localhost:8080/primefaces-test/test.xhtml

You will get this stack trace:
```
java.lang.NullPointerException
        at org.omnifaces.cdi.eager.EagerBeansWebListener.requestInitialized(EagerBeansWebListener.java:70)
        at org.eclipse.jetty.server.handler.ContextHandler.requestInitialized(ContextHandler.java:1387)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1425)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:191)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
        at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] /primefaces-test/test.xhtml
java.lang.NullPointerException
    at org.omnifaces.application.OmniApplication.createConverter (OmniApplication.java:82)
    at org.primefaces.config.PrimeConfiguration.<init> (PrimeConfiguration.java:78)
    at org.primefaces.context.PrimeApplicationContext.<init> (PrimeApplicationContext.java:88)
    at org.primefaces.context.PrimeApplicationContext.getCurrentInstance (PrimeApplicationContext.java:221)
    at org.primefaces.context.PrimeApplicationContext.getCurrentInstance (PrimeApplicationContext.java:209)
    at org.primefaces.context.PrimeRequestContext.getApplicationContext (PrimeRequestContext.java:199)
    at org.primefaces.context.PrimeFacesContext.<init> (PrimeFacesContext.java:60)
    at org.primefaces.context.PrimeFacesContextFactory.getFacesContext (PrimeFacesContextFactory.java:59)
    at javax.faces.webapp.FacesServlet.prepareFacesContext (FacesServlet.java:253)
    at javax.faces.webapp.FacesServlet.service (FacesServlet.java:181)
    at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service (ServletHolder.java:1450)
    at org.eclipse.jetty.servlet.ServletHolder.handle (ServletHolder.java:799)
    at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter (ServletHandler.java:1626)
    at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter (WebSocketUpgradeFilter.java:228)
    at org.eclipse.jetty.servlet.FilterHolder.doFilter (FilterHolder.java:193)
    at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter (ServletHandler.java:1601)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle (ServletHandler.java:548)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle (SecurityHandler.java:602)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:235)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle (SessionHandler.java:1624)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle (ScopedHandler.java:233)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle (ContextHandler.java:1434)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:188)
    at org.eclipse.jetty.servlet.ServletHandler.doScope (ServletHandler.java:501)
    at org.eclipse.jetty.server.session.SessionHandler.doScope (SessionHandler.java:1594)
    at org.eclipse.jetty.server.handler.ScopedHandler.nextScope (ScopedHandler.java:186)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope (ContextHandler.java:1349)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle (ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle (ContextHandlerCollection.java:191)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle (HandlerCollection.java:146)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle (HandlerWrapper.java:127)
    at org.eclipse.jetty.server.Server.handle (Server.java:516)
    at org.eclipse.jetty.server.HttpChannel.lambda$handle$1 (HttpChannel.java:388)
    at org.eclipse.jetty.server.HttpChannel.dispatch (HttpChannel.java:633)
    at org.eclipse.jetty.server.HttpChannel.handle (HttpChannel.java:380)
    at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:277)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded (AbstractConnection.java:311)
    at org.eclipse.jetty.io.FillInterest.fillable (FillInterest.java:105)
    at org.eclipse.jetty.io.ChannelEndPoint$1.run (ChannelEndPoint.java:104)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob (QueuedThreadPool.java:883)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run (QueuedThreadPool.java:1034)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by BalusC** [comment] 2021-08-21 11:04
At first sight it looks like CDI is not ready at that moment. I guess I'll have to debug.

---

Update 1: indeed, when OmniApplication is constructed,
```
	public OmniApplication(Application wrapped) {
		super(wrapped);
		converterManager = getReference(ConverterManager.class);
		validatorManager = getReference(ValidatorManager.class);
	}
```
then `getReference()` returned `null` because this line in `BeansLocal#resolve()`
```
		Set<Bean<?>> beans = beanManager.getBeans(beanClass, qualifiers);
```
unexpectedly returned an empty set.

---

Update 2: as quick test I swapped OWB for Weld and it worked right away (ignoring unrelated exceptions in log):
```
java.lang.NullPointerException: charsetName
    at java.lang.String.<init> (String.java:464)
    at java.io.ByteArrayOutputStream.toString (ByteArrayOutputStream.java:278)
    at org.primefaces.extensions.resourcehandler.ThemeAccentColorResource.getContent (ThemeAccentColorResource.java:94)
    at org.primefaces.extensions.resourcehandler.ThemeAccentColorResource.getInputStream (ThemeAccentColorResource.java:78)
    at org.apache.myfaces.application.ResourceHandlerImpl.handleResourceRequest (ResourceHandlerImpl.java:631)
```

So it's again OWB behaving odd in some way .. I'll have to analyze what exactly needs to be (re)configured for OWB in Jetty.

**Comment by BalusC** [comment] 2021-08-21 11:48
Okay, the cause was this line in `openwebbeans.properties` file of the project:
```
org.apache.webbeans.scanExtensionJars=false
```
Putting back to `true` fixed it.

Not an OmniFaces problem, closing off.

**Comment by melloware** [comment] 2021-08-21 11:49
Ahhh sorry about that!  Thank you!

**Closed as completed by BalusC** 2021-08-21 11:48 UTC
