### ISSUE TITLE
OmniFaces 2.5.1 conflict with CDI @ConversationScoped

### ISSUE THREAD

**Issue by ricksouzaa** [omnifaces/omnifaces#329] opened 2016-11-16 20:56 UTC
I'm using the below versions and I am having trouble with the CDI @ConversationScoped.
The application is losing the state of the objects in the CDI Bean.

When I send a request to server into the conversation it's starting a new conversation without perform conversation.begin() in the server side. It's always start a new conversation with each request.

Tomcat 8.5.8
Mojarra 2.2.14
Weld Servlet 2.4.0.Final
Primefaces 6.0
OmniFaces 2.5.1

**Comment by BalusC** [comment] 2016-11-25 12:13
I can't reproduce this problem. Theoretically, I can't think of any causes. Does the problem really disappear when you remove OmniFaces? If not, then your problem is caused elsewhere. E.g. you're submitting a form which was rendered before the conversation has started. You'd better use <f:viewAction> to start the conversation.

**Comment by ricksouzaa** [comment] 2016-11-25 16:22
It happen only in OmniFaces 2.5.1. When I change it to 2.4 it work fine.

If you want you can see my pom file.
[pom.xml.zip](https://github.com/omnifaces/omnifaces/files/613608/pom.xml.zip)

**Comment by BalusC** [comment] 2016-11-25 16:33
I can't reproduce this problem in 2.5.1. It's likely related to #281. A reproducer will be helpful.

**Comment by ricksouzaa** [comment] 2016-11-25 16:41
How could I reproduce this problem for you? Is there any way to do it?

**Comment by BalusC** [comment] 2016-11-25 16:50
Just create smallest possible web project which demonstrates the problem. You can send/link a WAR file here or create a Github project on this.

**Comment by BalusC** [comment] 2016-12-18 22:01
Closing off as no-repro and no feedback for long time. Please open a new issue if you have a reproducer.

**Closed by BalusC** 2016-12-18 22:01 UTC

**Comment by ricksouzaa** [comment] 2017-02-05 19:03
Hi there!

I'm writting just to talk to you that the link bellow fixed my problem.

http://stackoverflow.com/questions/42039554/conversationscoped-bean-behaves-as-requestscoped-since-omnifaces-2-5-facesview
