### ISSUE TITLE
FullAjaxExceptionHandlerFactory and ProjectStage=Production

### ISSUE THREAD

**Issue by svrolanski** [omnifaces/omnifaces#249] opened 2016-05-16 18:38 UTC
Hi,

Using omnifaces 1.13, primefaces 5.3, mojarra 2.2.10, running on Tomcat 7.0.59
When I set ProjectStage to Production I don't get the error page shown.
`<context-param>`
	`<param-name>javax.faces.PROJECT_STAGE</param-name>`
	`<param-value>Production</param-value>`
`</context-param>`

The faces-config.xml also has:
`<resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>`
`<resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>`

This page works: (I click the button, exception is thrown, error page is shown)

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
	<h:body>
		<f:view contentType="text/html" encoding="UTF-8">
			<h:form>
				<p:commandButton value="Throw NPE" actionListener="#{bwLogin.clickOK()}"/>
			</h:form>
		</f:view>
	</h:body>
</html>
`

But this page doesn't (click the button, exception is thrown, I get a blank page, I just added the empty <h:head> tag, I need the head tag for many things, scripts, css, favicon, ...)

`<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui" xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
	<h:head>
	</h:head>
	<h:body>
		<f:view contentType="text/html" encoding="UTF-8">
			<h:form>
				<p:commandButton value="Throw NPE" actionListener="#{bwLogin.clickOK()}"/>
			</h:form>
		</f:view>
	</h:body>
</html>`

Now if I change "ProjectStage=Development", both pages works.
Think this is a omnifaces issue not being able to render the page?

Regards,
Sergio

**Comment by BalusC** [comment] 2016-05-18 08:42
This all works just fine for me. Your problem is ambiguous and suggests that you don't have a valid JSF page declared as error page. Did you make sure that your error page `<location>` represents a valid JSF view ID whose URL is also covered by `FacesServlet`?

**Comment by svrolanski** [comment] 2016-05-30 14:41
Sorry for the wait (this issue not a priority on my list, since I can workdaround it). My custom error page is shown when there is no <h:head> (ProjectStage=Development), so I guess the page is valid. I mentioned the ResourceHandler because I think they deal with head tag. I willl test without those later.

**Comment by BalusC** [comment] 2016-06-03 12:41
A reproducer project would be helpful.

**Comment by BalusC** [comment] 2016-06-30 07:54
Closing off. Still can't reproduce this and there's no reproducer. If you have a reproducer, please open a new issue.

**Closed by BalusC** 2016-06-30 07:54 UTC

**Comment by svrolanski** [comment] 2016-08-11 15:05
It was indeed a malformed error page. Some bad javascript code was enabled when compiled for production release. Fixed the javascript code and everything is back to normal.
