### ISSUE TITLE
validateUnique - keep specified field valid regardless of input

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#781] opened 2023-12-19 18:20 UTC
I tried using _validateUnique_ for a contact form where the user must enter a phone number and can optional provide a second one.

When using `validateUnique` like following the model data is lost on validation error and the _phone1_ field is also empty.
This problem is even more problematic with persistent existing data of a customer. The user must abort the editing process to not loose the _phone1_ data.

`<o:validateUnique components="phone1 phone2" showMessageFor="phone2" message="Phone2 must be different.">`.

In this example the input _phone1_ is valid, regardless what user enters into _phone2_ so _phone2_ should only be marked as invalid and data should not be lost in model for _phone1_.

Maybe a new attribute like _componentsValidate="phone2"_ could solve this issue, so that _phone1_ value will be used for comparison but not marked as invalid and so model value will be updated.

**Comment by BalusC** [comment] 2024-01-21 19:36
Norepro on demo section of https://showcase.omnifaces.org/validators/validateUnique

Can you provide a reproducer?

**Comment by BalusC** [comment] 2024-01-21 20:26
Ok, took a closer look at source code, this is reproducible when following 2 conditions are met:

- validator is placed *after* all the components
- INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL context param is set to `true`

The culprit is in https://github.com/jakartaee/faces/blob/d6cc6c5b0f0016725f32917fa8291f38116a3057/api/src/main/java/jakarta/faces/component/UIInput.java#L287 and then the https://github.com/eclipse-ee4j/mojarra/blob/350fbbea7fe3b2c02eb416934cdebb2c0f9830da/impl/src/main/java/com/sun/faces/renderkit/html_basic/HtmlBasicRenderer.java#L295 simply renders submitted value as empty string instead of model value.

**Comment by BalusC** [comment] 2024-02-03 14:11
Fixed in Mojarra side.

Work around for now, put validator *before* the target components, as shown in showcase.

**Comment by BalusC** [comment] 2024-02-17 15:43
Fix has been revered in Mojarra side because a TCK failed. I need to take a second look.

**Closed as completed** 2024-03-30 14:55 UTC

**Comment by djmj** [comment] 2024-03-31 17:55
Thanks for your workaround, we will use it for now.
