### ISSUE TITLE
omnifaces-2.0.jar  undeploy problem (classloader leak)

### ISSUE THREAD

**Issue by ratcashdev** [omnifaces/omnifaces#115] opened 2015-03-12 22:12 UTC
I have added omnifaces-2.0.jar via maven to my project.
After a deploy/redeploy cycle on Glassfish 4.1 the following files are marked as stale (.glassfishStaleFiles):
```
WEB-INF/
WEB-INF/lib/
WEB-INF/lib/omnifaces-2.0.jar
```

VisualVM shows several class instances still loaded:
```
this     - value: org.omnifaces.component.validator.ValidateOrder$Type #1
 <- GTE     - class: org.omnifaces.component.validator.ValidateOrder$Type, value: org.omnifaces.component.validator.ValidateOrder$Type #1
  <- [210]     - class: java.lang.Object[], value: org.omnifaces.component.validator.ValidateOrder$Type class ValidateOrder$Type
   <- elementData     - class: java.util.Vector, value: java.lang.Object[] #23510
    <- classes     - class: org.glassfish.web.loader.WebappClassLoader, value: java.util.Vector #671
     <- contextClassLoader (thread object)     - class: java.util.TimerThread, value: org.glassfish.web.loader.WebappClassLoader #2
```
The culprit seems to be a Timer holding some references. Would be good to remove this on undeploy.

**Comment by BalusC** [comment] 2015-03-25 09:18
Not sure why GlassFish is doing that. It are runnables held as an enum constant. Can you try 2.1-SNAPSHOT? Those runnables are since then serializable. If that doesn't work out too, we'll look closer.

**Comment by ratcashdev** [comment] 2015-03-25 23:41
The issue is the same also with 2.1-SNAPSHOT (omnifaces-2.1-20150325.081508-18.jar).

**Comment by BalusC** [comment] 2015-03-26 08:20
I refactored out the runnables from the enum. Can you try today's snapshot?

**Comment by ratcashdev** [comment] 2015-03-26 14:19
Tried with the latest snapshot. Forced me to make some Principals serializable, but still does not work.
``` Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project invoicer-server: Failed to clean project: Failed to delete ...\WEB-INF\lib\omnifaces-2.1-SNAPSHOT.jar -> [Help 1]

**Comment by BalusC** [comment] 2015-03-26 21:09
Is it still `org.omnifaces.component.validator.ValidateOrder$Type`?

**Comment by ratcashdev** [comment] 2015-03-27 07:49
To be clear: ValidateOrder is not the only class remaining loaded. There are approx a dozen of them. However, it looks like the problem may be somewhere else. I'll try to validate this finding on an almost empty j2ee project with no extra dependencies.

**Comment by ratcashdev** [comment] 2015-03-27 08:11
All right. So it is indeed OmniFaces.jar. Just by adding the dependency to an otherwise harmless j2ee maven project (created using the com.airhacks#javaee7-essentials-archetype ), causes the "Clean" or "Clean & Build" commands to fail, as long as the project is deployed to Glassfish. Without this dependency all is ok. I tried to add a random other dependency (e.g. logback). It was still unloadable.

The interesting part is that since it's only a dependency, the heap-dump of Glassfish (actually, Payara's latest release) analyzed using VisualVM does not reveal any omnifaces classes loaded. Yet the library can't be undeployed.

I Have a maven project demonstrating the issue. Where can I upload it?

**Comment by ratcashdev** [comment] 2015-03-27 08:22
See the diff between a project without and with omnifaces dependency.
```
--- from_file
+++ WARN:   WELD-000411: Observer method [BackedAnnota
@@ -1,3 +1,8 @@
 WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
+WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] org.glassfish.sse.impl.ServerSentEventCdiExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>, BeanManager) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
+WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.omnifaces.VetoAnnotatedTypeExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
 WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
 WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
+WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] private org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
+WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.omnifaces.VetoAnnotatedTypeExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
+WARN:   WELD-000411: Observer method [BackedAnnotatedMethod] public org.glassfish.jms.injection.JMSCDIExtension.processAnnotatedType(@Observes ProcessAnnotatedType<Object>) receives events for all annotated types. Consider restricting events using @WithAnnotations or a generic type with bounds.
```
It looks like as if omnifaces got loaded twice.

**Comment by ratcashdev** [comment] 2015-03-27 09:46
Even version 1.4 (the first with FacesViews) has this problem

**Comment by BalusC** [comment] 2015-03-27 12:53
What do you mean with

> I tried to add a random other dependency (e.g. logback). It was still unloadable.

Are you seeing the same problem with logback (and any other dependency?)

Those WELD warnings are known (see also javadoc of that class) and don't seem to be related in any way.

**Comment by ratcashdev** [comment] 2015-03-27 12:57
What I tried to say with logback, that if the WEB-INF/lib is not empty and contain a 'random other' jar (e.g. logback) then it was still possible to unload/reload the app without any stale file. mvn clean also worked.

**Comment by BalusC** [comment] 2015-03-27 13:23
Looks related: https://java.net/jira/browse/GLASSFISH-21283

**Comment by ratcashdev** [comment] 2015-03-27 21:49
In order to make it undeployable, I needed to remove the beans.xml, and both files under META-INF/services. Certainly, it does not really work this way :)

**Comment by BalusC** [comment] 2015-11-26 10:16
Closing off as technical problem is in GF/Payara side.

**Closed by BalusC** 2015-11-26 10:16 UTC

**Comment by smillidge** [comment] 2015-12-12 20:24
I can't reproduce any problem in Payara deploying a war with omnifaces on Linux or Windows. Application with Omnifaces redeploys fine on both platforms without delays and there are no omnifaces object instances in the heap after undeploy. This is on the latest snapshot Payara Builds

**Comment by BalusC** [comment] 2015-12-12 21:56
Good to hear! Thank you for the feedback.
